const {   ObjectId } = require('mongodb');
const path = require('path');
const fs = require('fs');

const util = require('util');


const writeFileAsync = util.promisify(fs.writeFile);
const mkdirAsync = util.promisify(fs.mkdir);
let input = [
	{
		"fieldName" : "Vendor_Name",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : false,
		"show" : false,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Details",
		"displayName" : "AnchorKey",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 1,
		"ord" : 2,
		"prompts" : "",
		"_id" : new ObjectId("61a906ec471989234f59f570")
	},
	{
		"fieldName" : "mapper",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : false,
		"show" : false,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Details",
		"displayName" : "AnchorKey",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 1,
		"ord" : 2,
		"prompts" : "",
		"_id" : new ObjectId("61a906ec471989234f59f570")
	},
	{
		"fieldName" : "mapper",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : false,
		"show" : false,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Details",
		"displayName" : "AnchorKey",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 1,
		"ord" : 2,
		"prompts" : "",
		"_id" : new ObjectId("61a906ec471989234f59f570")
	},
	{
		"fieldName" : "consignor's name",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : false,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Details",
		"displayName" : "consignor's name",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "yes",
		"rw" : 1,
		"ord" : 1,
		"prompts" : "Extract the consignor's name",
		"_id" : new ObjectId("61a906ec471989234f59f568")
	},
	{
		"fieldName" : "Consignor's address",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : false,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Details",
		"displayName" : "Consignor's Address",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "yes",
		"rw" : 2,
		"ord" : 1,
		"prompts" : "Find and extract the Consignor's Address",
		"_id" : new ObjectId("61a906ec471989234f59f570")
	},
	{
		"fieldName" : "Consignor's Tax Reference ",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Details",
		"displayName" : "Consignor's Tax Reference",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "yes",
		"rw" : 2,
		"ord" : 1,
		"prompts" : "Identify and extract Consignor's Tax Reference",
		"_id" : new ObjectId("61a906ec471989234f59f570")
	},
	{
		"fieldName" : "consignee's name",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Details",
		"displayName" : "Consignee's name",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "yes",
		"rw" : 2,
		"ord" : 1,
		"prompts" : "Identify and extract consignee's name",
		"_id" : new ObjectId("61a906ec471989234f59f570")
	},
	{
		"fieldName" : "consignee's Address",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Details",
		"displayName" : "Consignee's Address",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "yes",
		"rw" : 2,
		"ord" : 1,
		"prompts" : "Extract the consignee's Address",
		"_id" : new ObjectId("61a906ec471989234f59f570")
	},
	{
		"fieldName" : "Consignee's Tax Reference",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Details",
		"displayName" : "Consignee's Tax Reference",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "yes",
		"rw" : 2,
		"ord" : 1,
		"prompts" : "Identify and extract Consignee's Tax Reference",
		"_id" : new ObjectId("61a906ec471989234f59f570")
	},
	{
		"fieldName" : "notify party's name",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Details",
		"displayName" : "Notify party's name",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "yes",
		"rw" : 2,
		"ord" : 1,
		"prompts" : "Identify and extract the notify party's name.",
		"_id" : new ObjectId("61a906ec471989234f59f570")
	},
	{
		"fieldName" : "Shipper's Reference",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Details",
		"displayName" : "Shipper's Reference",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "yes",
		"rw" : 2,
		"ord" : 1,
		"prompts" : "Extract the shipper's reference number from the Sea Waybill.",
		"_id" : new ObjectId("61a906ec471989234f59f570")
	},
	{
		"fieldName" : "Bill of Lading Number",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Details",
		"displayName" : "Bill of Lading Number",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "yes",
		"rw" : 2,
		"ord" : 1,
		"prompts" : "extract the Bill of Lading number from the Sea Waybill, this number is alphanumeric with capital letters",
		"_id" : new ObjectId("61a906ec471989234f59f570")
	},
	{
		"fieldName" : "Forwarder's Reference",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Details",
		"displayName" : "Forwarder's Reference",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "yes",
		"rw" : 2,
		"ord" : 1,
		"prompts" : "Extract the forwarder's reference number from the Sea Waybill.",
		"_id" : new ObjectId("61a906ec471989234f59f570")
	},
	{
		"fieldName" : "Unique Consignment Reference",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Details",
		"displayName" : "Unique Consignment Reference",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "yes",
		"rw" : 2,
		"ord" : 1,
		"prompts" : "Identify and extract the unique consignment reference from the Sea Waybill.",
		"_id" : new ObjectId("61a906ec471989234f59f570")
	},
	{
		"fieldName" : "carrier's name",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Details",
		"displayName" : "carrier's name",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "yes",
		"rw" : 2,
		"ord" : 1,
		"prompts" : "Extract the carrier's name",
		"_id" : new ObjectId("61a906ec471989234f59f570")
	},
	{
		"fieldName" : "Additional Notify Party",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Details",
		"displayName" : "Additional Notify Party",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "yes",
		"rw" : 2,
		"ord" : 1,
		"prompts" : "Extract the Additional Notify Party from sea waybill.",
		"_id" : new ObjectId("61a906ec471989234f59f570")
	},
	{
		"fieldName" : "Pre-Carriage By",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Details",
		"displayName" : "Pre-Carriage By",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "yes",
		"rw" : 2,
		"ord" : 1,
		"prompts" : "Identify and extract the pre-carriage details from the Sea Waybill.",
		"_id" : new ObjectId("61a906ec471989234f59f570")
	},
	{
		"fieldName" : "Place of Receipt",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Details",
		"displayName" : "Place of Receipt",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "yes",
		"rw" : 2,
		"ord" : 1,
		"prompts" : "Extract the place of receipt from the Sea Waybill.",
		"_id" : new ObjectId("61a906ec471989234f59f570")
	},
	{
		"fieldName" : "Vessel/Voyage No",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Details",
		"displayName" : "Vessel/Voyage No",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "yes",
		"rw" : 2,
		"ord" : 1,
		"prompts" : "Extract the Vessel/Voyage No from sea waybill.",
		"_id" : new ObjectId("61a906ec471989234f59f570")
	},
	{
		"fieldName" : "Port of Loading",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Details",
		"displayName" : "Port of Loading",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "yes",
		"rw" : 2,
		"ord" : 1,
		"prompts" : "Extract the Port of Loading from sea waybill.",
		"_id" : new ObjectId("61a906ec471989234f59f570")
	},
	{
		"fieldName" : "Port of Discharge",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Details",
		"displayName" : "Port of Discharge",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "yes",
		"rw" : 2,
		"ord" : 1,
		"prompts" : "Extract the Port of Discharge from sea waybill.",
		"_id" : new ObjectId("61a906ec471989234f59f570")
	},
	{
		"fieldName" : "Final Place of Delivery by On-Carrier",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Details",
		"displayName" : "Final Place of Delivery by On-Carrier",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "yes",
		"rw" : 2,
		"ord" : 1,
		"prompts" : "Identify and extract the final place of delivery by on-carrier from the Sea Waybill.",
		"_id" : new ObjectId("61a906ec471989234f59f570")
	},
	{
		"fieldName" : " Transport Unit ID",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Details",
		"displayName" : "Transport Unit ID",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "yes",
		"rw" : 2,
		"ord" : 1,
		"prompts" : "Extract the Transport Unit ID from sea waybill.",
		"_id" : new ObjectId("61a906ec471989234f59f570")
	},
	{
		"fieldName" : "Number and marks ",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Details",
		"displayName" : "Number/Marks",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "yes",
		"rw" : 2,
		"ord" : 1,
		"prompts" : "Extract the marks and Numbers from sea waybill.",
		"_id" : new ObjectId("61a906ec471989234f59f570")
	},
	{
		"fieldName" : "Kind of Packages",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Details",
		"displayName" : " Kind of Packages",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "yes",
		"rw" : 2,
		"ord" : 1,
		"prompts" : "Extract the No Of PKGS (number of packages) or kind of packages from sea waybill.",
		"_id" : new ObjectId("61a906ec471989234f59f570")
	},
	{
		"fieldName" : "Gross Weight",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Details",
		"displayName" : "Gross Weight",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "yes",
		"rw" : 2,
		"ord" : 1,
		"prompts" : "Extract the Gross Weight of the shipment from sea waybill.",
		"_id" : new ObjectId("61a906ec471989234f59f570")
	},
	{
		"fieldName" : "Measurement",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Details",
		"displayName" : "Measurement",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "yes",
		"rw" : 2,
		"ord" : 1,
		"prompts" : "Extract the measurements associated with the shipment from the Sea Waybill.",
		"_id" : new ObjectId("61a906ec471989234f59f570")
	},
	{
		"fieldName" : "Container No(s)",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Details",
		"displayName" : "Container No(s)",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "yes",
		"rw" : 2,
		"ord" : 1,
		"prompts" : "Extract the Container No from the Sea Waybill.",
		"_id" : new ObjectId("61a906ec471989234f59f570")
	},
	{
		"fieldName" : "Seal No",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Details",
		"displayName" : "Seal No",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "yes",
		"rw" : 2,
		"ord" : 1,
		"prompts" : "Extract the Seal No from the Sea Waybill.",
		"_id" : new ObjectId("61a906ec471989234f59f570")
	},
	{
		"fieldName" : "Freight Details",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Details",
		"displayName" : "Freight Details",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "yes",
		"rw" : 2,
		"ord" : 1,
		"prompts" : "Extract the Freight Details from the Sea Waybill.",
		"_id" : new ObjectId("61a906ec471989234f59f570")
	},
	{
		"fieldName" : "Rate",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Details",
		"displayName" : "Rate",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "yes",
		"rw" : 2,
		"ord" : 1,
		"prompts" : "Extract the Rate from the Sea Waybill.",
		"_id" : new ObjectId("61a906ec471989234f59f570")
	},
	{
		"fieldName" : "Freight Payable At",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Details",
		"displayName" : "Freight Payable At",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "yes",
		"rw" : 2,
		"ord" : 1,
		"prompts" : "Extract the location where Freight Payable At from the Sea Waybill.",
		"_id" : new ObjectId("61a906ec471989234f59f570")
	},
	{
		"fieldName" : "Number of Original Bill of Lading",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Details",
		"displayName" : "Number of Original Bill of Lading",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "yes",
		"rw" : 2,
		"ord" : 1,
		"prompts" : "Extract the Number of Original Bill of Lading from the Sea Waybill.",
		"_id" : new ObjectId("61a906ec471989234f59f570")
	},
	{
		"fieldName" : "Date of Issue",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Details",
		"displayName" : "Date of Issue",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "yes",
		"rw" : 2,
		"ord" : 1,
		"prompts" : "Extract the Date of Issue from the Sea Waybill.",
		"_id" : new ObjectId("61a906ec471989234f59f570")
	},
	{
		"fieldName" : "Place",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Details",
		"displayName" : "Place",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "yes",
		"rw" : 2,
		"ord" : 1,
		"prompts" : "Extract the Place from the Sea Waybill.",
		"_id" : new ObjectId("61a906ec471989234f59f570")
	},
	{
		"fieldName" : "Authenticating Signature",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Details",
		"displayName" : "Authenticating Signature",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "yes",
		"rw" : 2,
		"ord" : 1,
		"prompts" : "Extract the Authenticating Signature from the Sea Waybill.",
		"_id" : new ObjectId("61a906ec471989234f59f570")
	}
]
let output = input.map(item=>{
    let displayName = item.fieldName


    item.fieldName= item.fieldName.replace(/[^\w\s]/gi, '');

    item.fieldName= item.fieldName.trim().replace(/\s+/g, ' ');

    item.fieldName= item.fieldName.replace(/ /g, '_').toLowerCase();

    let obj = {
		"fieldName" : item.fieldName,
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Bill Details",
		"displayName" : displayName,
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"_id" :   new ObjectId("61a906ec471989234f59f570"),
		"prompts" : `Give me the ${displayName}, If it is not available, give 'Not Available in the Document'`
	}



    return obj;
})

let temp = new Date().getTime()

writeFileToLocation("newFiles/"+temp+".js",JSON.stringify(output))

async function writeFileToLocation(filePath, data) {
    try {
      const directoryPath = path.dirname(filePath); // Get the directory from filePath
      
      // Ensure the directory exists (create if it doesn't)
      if (!fs.existsSync(directoryPath)) {
        await mkdirAsync(directoryPath, { recursive: true });
      }
      
  
      // Write the file
      await writeFileAsync(filePath, data);
      console.log('File has been written successfully to', filePath);
    } catch (err) {
      console.error('Error writing file:', err);
    }
  }
console.log(output)
console.log(temp)