const {  } = require("mongodb")

let input = [
	{
		"fieldName" : "CompanyID",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "CompanyID",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the Company ID from the document, which is typically represented by the MID Code or similar identifier, such as 'MID Code: 25041524'.",
		"_id" : ("67ece74ca2199cc341f14dd0")
	},
	{
		"fieldName" : "UserID",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "UserID",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the UserID from the document, which is typically represented by a unique identifier associated with the exporter or consignee, such as 'MID Code' or 'IE Code'.",
		"_id" : ("67ece74ca2199cc341f14dd1")
	},
	{
		"fieldName" : "BranchCode",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "BranchCode",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the Branch Code from the document, typically found near the Exporter information or in the header section, and may be labeled as 'MID Code' or similar.",
		"_id" : ("67ece74ca2199cc341f14dd2")
	},
	{
		"fieldName" : "JobNo",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "JobNo",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the Job Number from the document, typically found near the Invoice Number or as a reference in the header section.",
		"_id" : ("67ece74ca2199cc341f14dd3")
	},
	{
		"fieldName" : "JobType",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "JobType",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the Job Type from the document, specifically looking for any section that describes the nature of the work or service being provided, such as 'Terms of Delivery and Payment' or any related context.",
		"_id" : ("67ece74ca2199cc341f14dd4")
	},
	{
		"fieldName" : "WorkingPeriod",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "WorkingPeriod",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the 'Working Period' information from the provided RC document, ensuring to identify any relevant dates or time frames mentioned in the context.",
		"_id" : ("67ece74ca2199cc341f14dd5")
	},
	{
		"fieldName" : "PageCount",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "PageCount",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the total number of pages indicated in the document, specifically looking for the phrase 'PAGE Number' followed by the page count.",
		"_id" : ("67ece74ca2199cc341f14dd6")
	},
	{
		"fieldName" : "PdfCount",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "PdfCount",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the total number of pages in the document, as indicated by the 'PAGE Number' section at the bottom of the page.",
		"_id" : ("67ece74ca2199cc341f14dd7")
	},
	{
		"fieldName" : "JobStatus",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "JobStatus",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the Job Status from the Registration Certificate document, ensuring to identify any relevant terms or phrases that indicate the current status of the job or application process.",
		"_id" : ("67ece74ca2199cc341f14dd8")
	},
	{
		"fieldName" : "FileName",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "FileName",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the 'FileName' from the document, ensuring to identify any relevant context or labels that indicate the file name, such as 'Invoice No.' or 'Exporter Ref.'.",
		"_id" : ("67ece74ca2199cc341f14dd9")
	},
	{
		"fieldName" : "InvoiceStartTime",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "InvoiceStartTime",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the 'Invoice Start Time' from the document, ensuring to identify any date or time format associated with the invoice number and date section, typically found near the top of the customs invoice.",
		"_id" : ("67ece74ca2199cc341f14dda")
	},
	{
		"fieldName" : "InvoiceResponseTime",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "InvoiceResponseTime",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the 'Invoice No. & Date' from the Customs Invoice document, ensuring to capture both the invoice number and the date as they appear together in the specified section.",
		"_id" : ("67ece74ca2199cc341f14ddb")
	},
	{
		"fieldName" : "Status",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "Status",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the 'IGST PAYMENT STATUS' from the customs invoice document, which indicates whether the payment of IGST is applicable for the export.",
		"_id" : ("67ece74ca2199cc341f14ddc")
	},
	{
		"fieldName" : "Client",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "Client",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the name and address of the client from the document, specifically looking for the section labeled 'Buyer (if other than Consignee)' or any similar designation that indicates the client information.",
		"_id" : ("67ece74ca2199cc341f14dde")
	},
	{
		"fieldName" : "IEC",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "IEC",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the IEC (Import Export Code) from the document, which is typically formatted as a 10-digit number and can be found near the GSTIN and PAN details.",
		"_id" : ("67ece74ca2199cc341f14ddf")
	},
	{
		"fieldName" : "Branch",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "Branch",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the 'Branch' information from the document, ensuring to identify any relevant details that indicate the specific branch location associated with the exporter or consignee.",
		"_id" : ("67ece74ca2199cc341f14de0")
	},
	{
		"fieldName" : "ExporterName",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "ExporterName",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the Exporter Name from the document, which is typically found near the top of the invoice, following the label 'Exporter'.",
		"_id" : ("67ece74ca2199cc341f14de1")
	},
	{
		"fieldName" : "InvoiceNo",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "InvoiceNo",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the Invoice Number from the document, which is typically labeled as 'Invoice No.' followed by the corresponding number and date.",
		"_id" : ("67ece74ca2199cc341f14de2")
	},
	{
		"fieldName" : "InvoiceDate",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "InvoiceDate",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the 'Invoice Date' from the document, which is typically found next to the 'Invoice No.' in the header section of the customs invoice.",
		"_id" : ("67ece74ca2199cc341f14de3")
	},
	{
		"fieldName" : "BuyerName",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "BuyerName",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the name of the buyer from the document, which is typically found below the label 'Buyer (if other than Consignee)' or under the label of 'Notify Party'.",
		"_id" : ("67ece74ca2199cc341f14ddd")
	},
	{
		"fieldName" : "BuyerOrderNo",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "BuyerOrderNo",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the 'Buyer's Order No.' from the document, which is typically found near the 'Invoice No. & Date' section, and is formatted as a series of numbers.",
		"_id" : ("67ece74ca2199cc341f14de4")
	},
	{
		"fieldName" : "OtherReference",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "OtherReference",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the 'Other Reference(s)' from the Customs Invoice document, which is typically located near the Exporter details and may include additional identifiers or order numbers.",
		"_id" : ("67ece74ca2199cc341f14de5")
	},
	{
		"fieldName" : "ConsigneeName",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "ConsigneeName",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the Consignee Name from the document, which is typically found near the label 'Consignee' and may include the name of the company or individual followed by their address.",
		"_id" : ("67ece74ca2199cc341f14de6")
	},
	{
		"fieldName" : "ConsigneeAdd",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "ConsigneeAdd",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the 'Consignee' address from the document, which is typically located after the term 'Consignee' and includes the name and address details.",
		"_id" : ("67ece74ca2199cc341f14de7")
	},
	{
		"fieldName" : "TermsOfPayment",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "TermsOfPayment",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the 'Terms of Delivery and Payment' section from the customs invoice, which includes details about payment terms and conditions, such as 'By Acceptance 30 Days From Cargo Receipt Date'.",
		"_id" : ("67ece74ca2199cc341f14deb")
	},
	{
		"fieldName" : "PaymentPeriod",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "PaymentPeriod",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the 'Terms of Delivery and Payment' section from the document, specifically looking for the payment period mentioned, such as 'By Acceptance 30 Days From Cargo Receipt Date'.",
		"_id" : ("67ece74ca2199cc341f14dec")
	},
	{
		"fieldName" : "CountryOfDischarge",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "CountryOfDischarge",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the 'Country of Discharge' from the document, which is typically located near the 'Port of Discharge' section, following the format 'Country of Discharge: [Country Name]'.",
		"_id" : ("67ece74ca2199cc341f14ded")
	},
	{
		"fieldName" : "PortOfDischarge",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "PortOfDischarge",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the 'Port of Discharge' information from the document, which is typically located near the shipping details section, following the format 'Port of Discharge' and is associated with the destination of the goods.",
		"_id" : ("67ece74ca2199cc341f14dee")
	},
	{
		"fieldName" : "SchemeCode",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "SchemeCode",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the Scheme Code from the document, which is typically found in the section detailing the Drawback Declaration Code, formatted as 'DBK001 & 003'.",
		"_id" : ("67ece74ca2199cc341f14def")
	},
	{
		"fieldName" : "CartonNo",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "CartonNo",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the 'No. & Kind of Pkgs' field from the Customs Invoice document, specifically looking for the carton number associated with the description of goods.",
		"_id" : ("67ece74ca2199cc341f14df0")
	},
	{
		"fieldName" : "OrderNo",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "OrderNo",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the 'Buyer's Order No.' from the document, which is typically found near the invoice details and may be labeled as 'Buyer's Order No. & Date'.",
		"_id" : ("67ece74ca2199cc341f14df1")
	},
	{
		"fieldName" : "KimballNo",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "KimballNo",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the 'Kimball No' from the provided RC document, ensuring to look for any section that lists identification numbers or codes related to the goods or shipment.",
		"_id" : ("67ece74ca2199cc341f14df2")
	},
	{
		"fieldName" : "QtyCode",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "QtyCode",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the quantity code from the document, li will tell what is the quantity code, it will be in english, FOr example, 'pcs','EA'",
		"_id" : ("67ece74ca2199cc341f14df3")
	},
	{
		"fieldName" : "Currency",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "Currency",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the currency mentioned in the document, specifically looking for the term 'CURRENCY' or any currency symbol such as '$' or 'USD' that indicates the type of currency used in the financial details.",
		"_id" : ("67ece74ca2199cc341f14df4")
	},
	{
		"fieldName" : "Terms",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "Terms",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the 'Terms of Delivery and Payment' section from the customs invoice, which includes details about the delivery terms and payment conditions.",
		"_id" : ("67ece74ca2199cc341f14df5")
	},
	{
		"fieldName" : "InvoiceValue",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "InvoiceValue",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the total amount chargeable from the customs invoice, specifically the value listed as 'Amount Chargeable' or 'Total' in the document.",
		"_id" : ("67ece74ca2199cc341f14df6")
	},
	{
		"fieldName" : "GarmentsIGSTPercentage",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "GarmentsIGSTPercentage",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the IGST Amount from the document, specifically looking for the section that mentions 'IGST Amount' followed by the corresponding value.",
		"_id" : ("67ece74ca2199cc341f14df7")
	},
	{
		"fieldName" : "HangerIGSTPercentage",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "HangerIGSTPercentage",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the IGST percentage from the document, specifically looking for the section that mentions 'IGST PAYMENT STATUS' or 'IGST Amount' to identify the applicable percentage.",
		"_id" : ("67ece74ca2199cc341f14df8")
	},
	{
		"fieldName" : "TotalGrossWeight",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "TotalGrossWeight",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the 'Gross Wt' value from the document, which is typically listed in kilograms and follows the format 'Gross Wt: [value] Kgs'.",
		"_id" : ("67ece74ca2199cc341f14df9")
	},
	{
		"fieldName" : "TotalNetWeight",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "TotalNetWeight",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the 'Nett Wt.' value from the document, which indicates the total net weight of the goods in kilograms.",
		"_id" : ("67ece823944651c078b4c7b3")
	},
	{
		"fieldName" : "TotalCarton",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "TotalCarton",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the total number of cartons from the document, specifically looking for the phrase 'Total' followed by the number of cartons listed.",
		"_id" : ("67ece823944651c078b4c7b4")
	},
	{
		"fieldName" : "TotalCBM",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "TotalCBM",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the 'Total CBM' value from the document, ensuring to look for any section that summarizes the total volume or cubic measurement of the goods being exported.",
		"_id" : ("67ece823944651c078b4c7b5")
	},
	{
		"fieldName" : "NotifyPartyName",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "NotifyPartyName",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the Notify Party Name from the document, typically found in the section detailing the consignee or buyer information, following the format of 'Notify Party:' or 'Buyer (if other than Consignee) NOTIFY PARTy' or similar indicators.\n                The below one is the sample ocr data : \n                Consignee\t\t  Buyer (if other than Consignee)\tGOODS DISPATCH FROM :\n                M/S.PRIMARK US CORP\t\t     NOTIFY PARTY\t       MAF CLOTHING PVT LTD\n                7171 GOODLETT FARMS PARKWAY\t   PRIMARK LIMITED       RAJATHADRIPURA VILLAGE, UNIT-3,\n                CORDOVA, TN 38016\t\t     ARTHUR RYAN HOUSE SYNO.59/3 AND 59/4, TUMAKURU, KIBBANAHALLI HOBLI,\n                USA\t\t\t\t22-24 PARNELL STREET TIPTUR TALUK, K.B. CR0SS, KARNATAKA - 572114\n                \n                from the above data, the NotifyPartyName is 'PRIMARK LIMITED ', becuase it is under notify party.\n                ",
		"_id" : ("67ece823944651c078b4c7b6")
	},
	{
		"fieldName" : "NotifyAddress",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "NotifyAddress",
		"isTable" : false,
		"tableName" : "",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the Notify Address from the document, specifically looking for the section that includes the term 'Notify Address'   or 'Buyer (if other than Consignee) NOTIFY PARTy' or  similar wording, followed by the address details.\n                \n                 The below one is the sample ocr data : \n                Consignee\t\t  Buyer (if other than Consignee)\tGOODS DISPATCH FROM :\n                M/S.PRIMARK US CORP\t\t     NOTIFY PARTY\t       MAF CLOTHING PVT LTD\n                7171 GOODLETT FARMS PARKWAY\t   PRIMARK LIMITED       RAJATHADRIPURA VILLAGE, UNIT-3,\n                CORDOVA, TN 38016\t\t     ARTHUR RYAN HOUSE SYNO.59/3 AND 59/4, TUMAKURU, KIBBANAHALLI HOBLI,\n                USA\t\t\t\t22-24 PARNELL STREET TIPTUR TALUK, K.B. CR0SS, KARNATAKA - 572114\n                \n                from the above data, the NotifyPartyAddress is 'ARTHUR RYAN HOUSE , 22-24 PARNELL STREET, DUBLIN 1, IRELAND ', becuase it is under notify party.\n                ",
		"_id" : ("67ece823944651c078b4c7b7")
	},
	{
		"fieldName" : "ItemDesc",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "ItemDesc",
		"isTable" : true,
		"tableName" : "Item Details",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the 'Description of Goods' from the customs invoice, which includes details about the items being exported, such as their type, material, and any specific features or packaging information.",
		"_id" : ("67ece823944651c078b4c7bb")
	},
	{
		"fieldName" : "Quantity",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "Quantity",
		"isTable" : true,
		"tableName" : "Item Details",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the 'Quantity' of goods listed in the document, specifically looking for numerical values associated with each item description under the 'Quantity' column.",
		"_id" : ("67ece823944651c078b4c7bd")
	},
	{
		"fieldName" : "Rate",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "Rate",
		"isTable" : true,
		"tableName" : "Item Details",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the 'Rate' from the document, specifically looking for the section that lists the quantity, unit, and corresponding rate for each item, as indicated in the table format.",
		"_id" : ("67ece823944651c078b4c7be")
	},
	{
		"fieldName" : "Amount",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "Amount",
		"isTable" : true,
		"tableName" : "Item Details",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the 'Amount' from the customs invoice, specifically the total chargeable amount listed at the bottom of the document, which is indicated as 'Amount Chargeable' followed by the numerical value.",
		"_id" : ("67ece823944651c078b4c7bf")
	},
	{
		"fieldName" : "InfoQty",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "InfoQty",
		"isTable" : true,
		"tableName" : "Item Details",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the quantity of the respective line time listed in the invoice table. specifically looking for the field labeled 'Total Weight ' associated with each item description. Quanity and this info qty are different, dont confuse. this infoqty only available along witth the description like  'Total Weight of Hangers : 8.40kgs'. Like these if preent then only have to extract, otherwise give empty",
		"_id" : ("67ece823944651c078b4c7c0")
	},
	{
		"fieldName" : "InfoUnitPrice",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "InfoUnitPrice",
		"isTable" : true,
		"tableName" : "Item Details",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the unit price of the goods from the customs invoice, specifically looking for the section that lists the rate per unit alongside the description of the goods. LIke the infoqty, infounitprice will only available with description. For example, 'Per Kg RATE : 1.53571' here 1.53571 is the value. If not present, dont extract.",
		"_id" : ("67ece823944651c078b4c7c1")
	},
	{
		"fieldName" : "ItemSlNo",
		"fieldType" : "string",
		"placeHolder" : "",
		"value" : "",
		"required" : true,
		"show" : true,
		"isDMSKey" : false,
		"isML" : true,
		"isBlockP" : true,
		"category" : "Customer Details",
		"displayName" : "ItemSlNo",
		"isTable" : true,
		"tableName" : "Item Details",
		"dateFormat" : "",
		"leftX" : 0,
		"rightX" : 0,
		"topY" : 0,
		"bottomY" : 0,
		"isImportant" : "",
		"rw" : 0,
		"ord" : 0,
		"prompts" : "Extract the 'ItemSlNo' from the document, which is typically found in the section listing the goods, often accompanied by descriptions and quantities.",
		"_id" : ("67ece823944651c078b4c7c2")
	}
]
input = input.filter(item=>!item.isTable)
output = []
input.forEach(item=>{
	output.push({
		"dbName" : item.fieldName,
		"uiName" : item.displayName,
		"description" : "",
		"dataType" : "String",
		"required" : true,
		"options" : [ ],
		"_id" :  ("6697554dd5f4e66c93bc939e")
	})
})

console.log(output)
