
let input =  [
    {
        "fieldName" : "AggrementNumber",
        "fieldType" : "string",
        "placeHolder" : "",
        "value" : "",
        "required" : false,
        "show" : true,
        "isDMSKey" : false,
        "isML" : true,
        "isBlockP" : true,
        "category" : "",
        "displayName" : "Aggrement Number",
        "isTable" : false,
        "tableName" : "",
        "dateFormat" : "",
        "leftX" : 0,
        "rightX" : 0,
        "topY" : 0,
        "bottomY" : 0,
        "isImportant" : "",
        "rw" : 0,
        "ord" : 0,
        "prompts" : "Extract me the Certificate number from the provided ocr data.. Extract only if it is there or available",
        "_id" : ("67add088fdb23d30ae38154d")
    },
    {
        "fieldName" : "ContractIssuedDate",
        "fieldType" : "string",
        "placeHolder" : "",
        "value" : "",
        "required" : false,
        "show" : true,
        "isDMSKey" : false,
        "isML" : true,
        "isBlockP" : true,
        "category" : "",
        "displayName" : "Contract Issued Date",
        "isTable" : false,
        "tableName" : "",
        "dateFormat" : "",
        "leftX" : 0,
        "rightX" : 0,
        "topY" : 0,
        "bottomY" : 0,
        "isImportant" : "",
        "rw" : 0,
        "ord" : 0,
        "prompts" : "Provide me the Contract Issued Date from the provided ocr data. Extract only if it is there or available",
        "_id" : ("67add088fdb23d30ae38154d")
    },
    {
        "fieldName" : "ContractType",
        "fieldType" : "string",
        "placeHolder" : "",
        "value" : "",
        "required" : false,
        "show" : true,
        "isDMSKey" : false,
        "isML" : true,
        "isBlockP" : true,
        "category" : "",
        "displayName" : "",
        "isTable" : false,
        "tableName" : "",
        "dateFormat" : "Contract Type",
        "leftX" : 0,
        "rightX" : 0,
        "topY" : 0,
        "bottomY" : 0,
        "isImportant" : "",
        "rw" : 0,
        "ord" : 0,
        "prompts" : "Extract the Contract Type , from the ocr data. You are a legal document classification expert. Given the OCR-extracted text from a legal agreement, identify the type of contract this document represents. Common contract types include: Service Agreement, License Agreement, Non-Disclosure Agreement (NDA), Employment Agreement, Addendum or Amendment, Lease Agreement, Partnership Agreement, Purchase or Sales Agreement, Confidentiality Agreement, Consulting Agreement, Master Service Agreement (MSA), and End User License Agreement (EULA). Return the most appropriate contract type as a single label, and justify your classification by quoting key phrases or clauses from the document that support your answer. If the type is unclear, return Unclear and briefly explain why a confident classification could not be made.  Extract only if it is there or available",
        "_id" : ("67add088fdb23d30ae38154d")
    },
    {
        "fieldName" : "FirstPartyName",
        "fieldType" : "string",
        "placeHolder" : "",
        "value" : "",
        "required" : false,
        "show" : true,
        "isDMSKey" : false,
        "isML" : true,
        "isBlockP" : true,
        "category" : "",
        "displayName" : "First Party Name",
        "isTable" : false,
        "tableName" : "",
        "dateFormat" : "",
        "leftX" : 0,
        "rightX" : 0,
        "topY" : 0,
        "bottomY" : 0,
        "isImportant" : "",
        "rw" : 0,
        "ord" : 0,
        "prompts" : "Extract the First Party Name, from the ocr data. Extract only if it is there or available",
        "_id" : ("67add088fdb23d30ae38154d")
    },
    {
        "fieldName" : "SecondPartyName",
        "fieldType" : "string",
        "placeHolder" : "",
        "value" : "",
        "required" : false,
        "show" : true,
        "isDMSKey" : false,
        "isML" : true,
        "isBlockP" : true,
        "category" : "",
        "displayName" : "Second Party Name",
        "isTable" : false,
        "tableName" : "",
        "dateFormat" : "",
        "leftX" : 0,
        "rightX" : 0,
        "topY" : 0,
        "bottomY" : 0,
        "isImportant" : "",
        "rw" : 0,
        "ord" : 0,
        "prompts" : "Extract the Second Party Name, from the provided ocr data. Extract only if it is there or available",
        "_id" : ("67add088fdb23d30ae38154d")
    },
    {
        "fieldName" : "FirstPartySignatory",
        "fieldType" : "string",
        "placeHolder" : "",
        "value" : "",
        "required" : false,
        "show" : true,
        "isDMSKey" : false,
        "isML" : true,
        "isBlockP" : true,
        "category" : "",
        "displayName" : "First Party Signatory",
        "isTable" : false,
        "tableName" : "",
        "dateFormat" : "",
        "leftX" : 0,
        "rightX" : 0,
        "topY" : 0,
        "bottomY" : 0,
        "isImportant" : "",
        "rw" : 0,
        "ord" : 0,
        "prompts" : "Extract the First Party Signatory, from the provided ocr data. Extract only if it is there or available",
        "_id" : ("67add088fdb23d30ae38154d")
    },
    {
        "fieldName" : "EffectiveDate",
        "fieldType" : "string",
        "placeHolder" : "",
        "value" : "",
        "required" : false,
        "show" : true,
        "isDMSKey" : false,
        "isML" : true,
        "isBlockP" : true,
        "category" : "",
        "displayName" : "Effective Date",
        "isTable" : false,
        "tableName" : "",
        "dateFormat" : "",
        "leftX" : 0,
        "rightX" : 0,
        "topY" : 0,
        "bottomY" : 0,
        "isImportant" : "",
        "rw" : 0,
        "ord" : 0,
        "prompts" : "Extract the Effective Date from the provided ocr data. Extract only if it is there or available",
        "_id" : ("67add088fdb23d30ae38154d")
    },
    {
        "fieldName" : "SecondPartySignatory",
        "fieldType" : "string",
        "placeHolder" : "",
        "value" : "",
        "required" : false,
        "show" : true,
        "isDMSKey" : false,
        "isML" : true,
        "isBlockP" : true,
        "category" : "",
        "displayName" : "Second Party Signatory",
        "isTable" : false,
        "tableName" : "",
        "dateFormat" : "",
        "leftX" : 0,
        "rightX" : 0,
        "topY" : 0,
        "bottomY" : 0,
        "isImportant" : "",
        "rw" : 0,
        "ord" : 0,
        "prompts" : "Extract the Second Party Signatory, from the provided ocr data. Extract only if it is there or available",
        "_id" : ("67add088fdb23d30ae38154d")
    },
    {
        "fieldName" : "StampDutyAmount",
        "fieldType" : "string",
        "placeHolder" : "",
        "value" : "",
        "required" : false,
        "show" : true,
        "isDMSKey" : false,
        "isML" : true,
        "isBlockP" : true,
        "category" : "",
        "displayName" : "Stamp Duty Amount",
        "isTable" : false,
        "tableName" : "",
        "dateFormat" : "",
        "leftX" : 0,
        "rightX" : 0,
        "topY" : 0,
        "bottomY" : 0,
        "isImportant" : "",
        "rw" : 0,
        "ord" : 0,
        "prompts" : "Extract the Stamp Duty Amount, from the provided ocr data. You are a legal document analysis expert. Given the OCR-extracted text from a legal agreement, identify and extract the Stamp Duty Amount paid for this document. Look for phrases such as Stamp Duty, Stamp Duty Paid, Stamp Duty Amount, E-Stamp, or any monetary value associated with government stamp duty payment. Return the amount along with its currency and quote the exact sentence or section from the text where this information is found. If no stamp duty information is available, return Not Found. Extract only if it is there or available",
        "_id" : ("67add088fdb23d30ae38154d")
    },
    {
        "fieldName" : "StampDutyPaidBy",
        "fieldType" : "string",
        "placeHolder" : "",
        "value" : "",
        "required" : false,
        "show" : true,
        "isDMSKey" : false,
        "isML" : true,
        "isBlockP" : true,
        "category" : "",
        "displayName" : "Stamp Duty Paid By",
        "isTable" : false,
        "tableName" : "",
        "dateFormat" : "",
        "leftX" : 0,
        "rightX" : 0,
        "topY" : 0,
        "bottomY" : 0,
        "isImportant" : "",
        "rw" : 0,
        "ord" : 0,
        "prompts" : "Extract the Stamp Duty Paid By, from the provided ocr data. You are a legal document analysis expert. Given the OCR-extracted text from a legal agreement, identify and extract who is responsible for paying the stamp duty. Look for phrases indicating which party bears the cost of the stamp duty, such as Stamp Duty shall be paid by, Stamp Duty to be borne by, or any similar wording. Return the responsible party as First Party, Second Party, Both Parties, Buyer, Seller, Tenant, Landlord, or Not Specified if unclear. Also quote the exact sentence or clause from the text that supports your answer. Extract only if it is there or available",
        "_id" : ("67add088fdb23d30ae38154d")
    },
    {
        "fieldName" : "aggrementTitle",
        "fieldType" : "string",
        "placeHolder" : "",
        "value" : "",
        "required" : false,
        "show" : true,
        "isDMSKey" : false,
        "isML" : true,
        "isBlockP" : true,
        "category" : "",
        "displayName" : "Aggrement Title",
        "isTable" : false,
        "tableName" : "",
        "dateFormat" : "",
        "leftX" : 0,
        "rightX" : 0,
        "topY" : 0,
        "bottomY" : 0,
        "isImportant" : "",
        "rw" : 0,
        "ord" : 0,
        "prompts" : "Extract the Aggrement Title, for example  'service Agreement' , or 'Leave & Licence Aggrement' or 'Adendum to Service Agreement'from the provided ocr data. You are a legal document analysis expert. Given the OCR-extracted text from a legal agreement, identify and extract the official title of the agreement. Look for text at the top of the document or in the opening section that clearly indicates the name or type of the agreement, such as Service Agreement, License Agreement, Lease Agreement, or Addendum to Agreement. Return the exact title as it appears in the document. If no clear title is found, return Not Found. . Extract only if it is there or available",
        "_id" : ("67add088fdb23d30ae38154d")
    },
    {
        "fieldName" : "AggrementExpiryDate",
        "fieldType" : "string",
        "placeHolder" : "",
        "value" : "",
        "required" : false,
        "show" : true,
        "isDMSKey" : false,
        "isML" : true,
        "isBlockP" : true,
        "category" : "",
        "displayName" : "Aggrement Expiry Date",
        "isTable" : false,
        "tableName" : "",
        "dateFormat" : "",
        "leftX" : 0,
        "rightX" : 0,
        "topY" : 0,
        "bottomY" : 0,
        "isImportant" : "",
        "rw" : 0,
        "ord" : 0,
        "prompts" : "Extract the Aggrement expiry Date, from the provided ocr data. You are a legal document analysis expert. Given the OCR-extracted text from a legal agreement, identify and extract the Agreement Expiry Date. Look for any statement that defines the end date of the agreement’s validity, such as phrases like shall expire on, shall remain in force until, or valid until. If the expiry is described as a duration from the Effective Date, calculate the expiry date if both values are available. Return the expiry date in a standard format like DD-MM-YYYY. If no expiry date is mentioned, return Not Found. Extract if there is any expiry date. Extract only if it is there or available",
        "_id" : ("67add088fdb23d30ae38154d")
    },
    {
        "fieldName" : "PartiesInvoled",
        "fieldType" : "string",
        "placeHolder" : "",
        "value" : "",
        "required" : false,
        "show" : true,
        "isDMSKey" : false,
        "isML" : true,
        "isBlockP" : true,
        "category" : "",
        "displayName" : "Parties Involved",
        "isTable" : false,
        "tableName" : "",
        "dateFormat" : "",
        "leftX" : 0,
        "rightX" : 0,
        "topY" : 0,
        "bottomY" : 0,
        "isImportant" : "",
        "rw" : 0,
        "ord" : 0,
        "prompts" : "Extract the Parties Involved, from the provided ocr data. Give me the details of all contracting entities involved. You are a legal document analysis expert. Given the OCR-extracted text from a legal agreement, identify and extract the names and roles of the parties involved in the contract. Focus on the introductory section where the agreement states who it is made between. Return the names of the entities or individuals along with their roles, such as First Party, Second Party, Service Provider, Client, Licensor, Licensee, etc. Quote the exact sentence or paragraph that contains this information. If the party details are not found, return Not Found. Extract only if it is there or available",
        "_id" : ("67add088fdb23d30ae38154d")
    },
    {
        "fieldName" : "PartyType",
        "fieldType" : "string",
        "placeHolder" : "",
        "value" : "",
        "required" : false,
        "show" : true,
        "isDMSKey" : false,
        "isML" : true,
        "isBlockP" : true,
        "category" : "",
        "displayName" : "Party Type",
        "isTable" : false,
        "tableName" : "",
        "dateFormat" : "",
        "leftX" : 0,
        "rightX" : 0,
        "topY" : 0,
        "bottomY" : 0,
        "isImportant" : "",
        "rw" : 0,
        "ord" : 0,
        "prompts" : "Extract the party type(Company, Individual, Vendor, Client), from the provided ocr data. You are a legal document analysis expert. Given the OCR-extracted text from a legal agreement, identify and extract the Party Type for each named party. Focus on descriptions where the document defines the role of a party using terms like Service Provider, Client, Licensor, Licensee, Seller, Buyer, Employer, Employee, Landlord, or Tenant. Return each party’s name along with their corresponding role. Also, quote the sentence or clause from which the role was identified. If the role is not clearly mentioned, return Not Specified. Extract only if it is there or available",
        "_id" : ("67add088fdb23d30ae38154d")
    },
    {
        "fieldName" : "RenewalClause",
        "fieldType" : "string",
        "placeHolder" : "",
        "value" : "",
        "required" : false,
        "show" : true,
        "isDMSKey" : false,
        "isML" : true,
        "isBlockP" : true,
        "category" : "",
        "displayName" : "Renewal Clause",
        "isTable" : false,
        "tableName" : "",
        "dateFormat" : "",
        "leftX" : 0,
        "rightX" : 0,
        "topY" : 0,
        "bottomY" : 0,
        "isImportant" : "",
        "rw" : 0,
        "ord" : 0,
        "prompts" : "Extract the Renewal Clause(Terms for extenion or renewal), from the provided ocr data. You are a legal document analysis expert. Given the OCR-extracted text from a legal agreement, identify and extract the Renewal Clause. Look for any language describing if and how the agreement can be renewed, including terms like automatic renewal, renewal upon mutual consent, or renewal notice period. Return a summary of the renewal terms in plain English, and also include the exact sentence or clause from the document where this information is stated. If no renewal clause is found, return Not Found.",
        "_id" : ("67add088fdb23d30ae38154d")
    },
    {
        "fieldName" : "PenaltyForLatePayment",
        "fieldType" : "string",
        "placeHolder" : "",
        "value" : "",
        "required" : false,
        "show" : true,
        "isDMSKey" : false,
        "isML" : true,
        "isBlockP" : true,
        "category" : "",
        "displayName" : "penalty for Late Payment",
        "isTable" : false,
        "tableName" : "",
        "dateFormat" : "",
        "leftX" : 0,
        "rightX" : 0,
        "topY" : 0,
        "bottomY" : 0,
        "isImportant" : "",
        "rw" : 0,
        "ord" : 0,
        "prompts" : "Extract the Penalty for late payment(fine strucutre for late payments), from the provided ocr data. You are a legal document analysis expert. Given the OCR-extracted text from a legal agreement, identify and extract any clause that specifies the penalty for late payment. Look for terms like late payment fee, overdue charges, interest on delayed payments, or payment grace period. Return a plain English summary of the penalty terms, and also include the exact sentence or clause from the document where this information is found. If no such clause is present, return Not Found.",
        "_id" : ("67add088fdb23d30ae38154d")
    },
    {
        "fieldName" : "LiablityForDamage",
        "fieldType" : "string",
        "placeHolder" : "",
        "value" : "",
        "required" : false,
        "show" : true,
        "isDMSKey" : false,
        "isML" : true,
        "isBlockP" : true,
        "category" : "",
        "displayName" : "Liability For Damage",
        "isTable" : false,
        "tableName" : "",
        "dateFormat" : "",
        "leftX" : 0,
        "rightX" : 0,
        "topY" : 0,
        "bottomY" : 0,
        "isImportant" : "",
        "rw" : 0,
        "ord" : 0,
        "prompts" : "Extract the Liablity For Damage(Tenent or owner responsiblity), from the provided ocr data. You are a legal document analysis expert. Given the OCR-extracted text from a legal agreement, identify and extract the clause that defines liability for damage. Look for terms indicating which party is responsible for damages, loss, or harm arising during the term of the agreement. Include whether any limits, exclusions, or indemnity clauses are mentioned. Return a plain English summary of the liability terms, and include the exact sentence or clause from the document. If no liability clause is found, return Not Found.",
        "_id" : ("67add088fdb23d30ae38154d")
    },
    {
        "fieldName" : "securityDeposit",
        "fieldType" : "string",
        "placeHolder" : "",
        "value" : "",
        "required" : false,
        "show" : true,
        "isDMSKey" : false,
        "isML" : true,
        "isBlockP" : true,
        "category" : "",
        "displayName" : "Security Deposit",
        "isTable" : false,
        "tableName" : "",
        "dateFormat" : "",
        "leftX" : 0,
        "rightX" : 0,
        "topY" : 0,
        "bottomY" : 0,
        "isImportant" : "",
        "rw" : 0,
        "ord" : 0,
        "prompts" : "extract the security deposit, along with this say, whether it is refundable or not, from the provided ocr data. You are a legal document analysis expert. Given the OCR-extracted text from a legal agreement, identify and extract any information related to a Security Deposit. Look for clauses mentioning an upfront payment intended as a safeguard against damage, loss, or non-compliance. Include the deposit amount, currency, refund conditions, and any terms for deductions or forfeiture. Return a summary in plain English along with the exact sentence or clause from the document. If no security deposit is mentioned, return Not Found.",
        "_id" : ("67add088fdb23d30ae38154d")
    },
    {
        "fieldName" : "PiricingAndPaymentTerms",
        "fieldType" : "string",
        "placeHolder" : "",
        "value" : "",
        "required" : false,
        "show" : true,
        "isDMSKey" : false,
        "isML" : true,
        "isBlockP" : true,
        "category" : "",
        "displayName" : "Pricing and Payment Terms",
        "isTable" : false,
        "tableName" : "",
        "dateFormat" : "",
        "leftX" : 0,
        "rightX" : 0,
        "topY" : 0,
        "bottomY" : 0,
        "isImportant" : "",
        "rw" : 0,
        "ord" : 0,
        "prompts" : "Extract the Pricing And paymnet terms(fixed, hourly, milestone-based), from the provided ocr data. You are a legal document analysis expert. Given the OCR-extracted text from a legal agreement, identify and extract the Pricing and Payment Terms. Look for details such as total payment amount, fee structure, installment or milestone payments, invoicing schedule, due dates, mode of payment, and tax applicability. Return a plain English summary of the payment obligations, and also include the exact sentence or clause from the document where this information is provided. If pricing and payment terms are not mentioned, return Not Found.",
        "_id" : ("67add088fdb23d30ae38154d")
    },
    {
        "fieldName" : "ServiceLevelAggregments",
        "fieldType" : "string",
        "placeHolder" : "",
        "value" : "",
        "required" : false,
        "show" : true,
        "isDMSKey" : false,
        "isML" : true,
        "isBlockP" : true,
        "category" : "",
        "displayName" : "ServiceLevelAggregements",
        "isTable" : false,
        "tableName" : "",
        "dateFormat" : "",
        "leftX" : 0,
        "rightX" : 0,
        "topY" : 0,
        "bottomY" : 0,
        "isImportant" : "",
        "rw" : 0,
        "ord" : 0,
        "prompts" : "Extract the Service Level Aggrements(SLAs), it is about uptime, delivery time, quality benchmarks, from the provided ocr data. You are a legal document analysis expert. Given the OCR-extracted text from a service agreement, identify and extract the Service Level Agreement (SLA) terms. Look for clauses that define service standards, response times, resolution times, uptime guarantees, or penalties for SLA violations. Provide a plain English summary of the SLA terms, and include the exact sentence or clause from the document. If no SLA is mentioned, return Not Found.",
        "_id" : ("67add088fdb23d30ae38154d")
    },
    {
        "fieldName" : "indemnificationsClause",
        "fieldType" : "string",
        "placeHolder" : "",
        "value" : "",
        "required" : false,
        "show" : true,
        "isDMSKey" : false,
        "isML" : true,
        "isBlockP" : true,
        "category" : "",
        "displayName" : "Indemnification Clause",
        "isTable" : false,
        "tableName" : "",
        "dateFormat" : "",
        "leftX" : 0,
        "rightX" : 0,
        "topY" : 0,
        "bottomY" : 0,
        "isImportant" : "",
        "rw" : 0,
        "ord" : 0,
        "prompts" : "Extract the idemnification clause, it is about who bears liablity for dmages, from the provided ocr data. You are a legal document analysis expert. Given the OCR-extracted text from a legal agreement, identify and extract the Indemnification Clause. Look for terms where one party agrees to indemnify, hold harmless, or defend the other party against losses, claims, liabilities, or damages. Provide a plain English summary of who is indemnifying whom and under what circumstances. Also include the exact sentence or clause from the document. If no indemnification clause is found, return Not Found.",
        "_id" : ("67add088fdb23d30ae38154d")
    },
    {
        "fieldName" : "TerminationClause",
        "fieldType" : "string",
        "placeHolder" : "",
        "value" : "",
        "required" : false,
        "show" : true,
        "isDMSKey" : false,
        "isML" : true,
        "isBlockP" : true,
        "category" : "",
        "displayName" : "Termination Clause",
        "isTable" : false,
        "tableName" : "",
        "dateFormat" : "",
        "leftX" : 0,
        "rightX" : 0,
        "topY" : 0,
        "bottomY" : 0,
        "isImportant" : "",
        "rw" : 0,
        "ord" : 0,
        "prompts" : "Extract the Termination clause(Notice Period or exxit conditions),from the provided ocr data. You are a legal document analysis expert. Given the OCR-extracted text from a legal agreement, identify and extract the Termination Clause. Look for any section that specifies the conditions, notice period, or rights of either party to end the contract. Summarize the termination terms in plain English and include the exact sentence or clause from the document. If no termination clause is found, return Not Found",
        "_id" : ("67add088fdb23d30ae38154d")
    },
    {
        "fieldName" : "Licence Fee",
        "fieldType" : "string",
        "placeHolder" : "",
        "value" : "",
        "required" : false,
        "show" : true,
        "isDMSKey" : false,
        "isML" : true,
        "isBlockP" : true,
        "category" : "",
        "displayName" : "Licence Fee",
        "isTable" : false,
        "tableName" : "",
        "dateFormat" : "",
        "leftX" : 0,
        "rightX" : 0,
        "topY" : 0,
        "bottomY" : 0,
        "isImportant" : "",
        "rw" : 0,
        "ord" : 0,
        "prompts" : "Extract the Licence Fee (rent Amount)(monthly rental value or corresponding rental value),  from the provided ocr data. You are a legal document analysis expert. Given the OCR-extracted text from a licensing agreement, identify and extract any information related to the Licence Fee. Look for clauses that mention the amount payable for the use of licensed material, the frequency of payments, and any associated conditions. Return a plain English summary of the licence fee terms, and include the exact sentence or clause from the document where this information is found. If no licence fee is mentioned, return Not Found.",
        "_id" : ("67add088fdb23d30ae38154d")
    }
],
output = []

input.forEach(element => {
    output.push({
        "dbName" : element.fieldName,
        "uiName" : element.displayName,
        "description" : "",
        "dataType" : "String",
        "required" : false,
        "options" : [ ],
        "isUniqueKey" : false,
        "_id" : ("67a0524d769051e8530df9bb")
    })
})

output.push({
    "dbName" : "createdAt",
    "uiName" : "Created At",
    "description" : "",
    "dataType" : "String",
    "required" : false,
    "options" : [ ],
    "isUniqueKey" : false,
    "_id" : ("67a0524d769051e8530df9bb")
})


console.log(output)