[
  {
    "Invoice Details": [
      {
        InvoiceSlNo: "1",
        InvoiceNo: "13935945",
        InvoiceDate: "03-MAR-2025",
        QtyCode: "EA",
        Currency: "USD",
        Terms: "FCA",
        TermsofPayment: "NET",
        InvoiceValue: "3246.24",
        SupplierName: "ARROW ELECTRONICS ASIA (S) PTE. LTD.",
        SupplierAdd1: "1 Tai Seng Avenue, #07-11/i2 & 13,",
        SupplierAdd2: "Tai Seng Exchange (Tower A)",
        SupplierAdd3: "Singapore,SG,New Territories",
        SupplierAdd4: "536464 singapore",
      },
      {
        InvoiceSlNo: "2",
        InvoiceNo: "13935947",
        InvoiceDate: "03-MAR-2025",
        QtyCode: "EA",
        Currency: "USD",
        Terms: "FCA",
        TermsofPayment: "NET",
        InvoiceValue: "801.13",
        SupplierName: "ARROW ELECTRONICS ASIA (S) PTE. LTD.",
        SupplierAdd1: "1 Tai Seng Avenue, #07-11/12 & 13,",
        SupplierAdd2: "Tai Seng Exchange (Tower A)",
        SupplierAdd3: "Singapore,SG,New Territories",
        SupplierAdd4: "536464 Singapore",
      },
    ],
    "Item Details": [
      {
        InvoiceSlNo: "1",
        itemSlNo: 1,
        ItemDesc: "DSP Fixed-Point 16bit 300MHz 208-Pin CSP-BGA TraY",
        Quantity: "389",
        Rate: "8.34510",
        Amount: "3246.24",
        PartNo: "",
        PONumber: "4201110888",
        ItemNETWEIGHT: "",
        ItemHSCODE: "8542310001",
        ItemCountry: "KR",
      },
      {
        InvoiceSlNo: "2",
        itemSlNo: 1,
        ItemDesc: "DSP Fixed-Point 16bit 300MHz 208-Pin CSP-BGA Tray",
        Quantity: "96",
        Rate: "8.34510",
        Amount: "801.13",
        PartNo: "",
        PONumber: "4201110888",
        ItemNETWEIGHT: "",
        ItemHSCODE: "8542310001",
        ItemCountry: "KR",
      },
    ],
  },
];
