[
  {
    Branch: "",
    CompanyID: "",
    UserID: "",
    BranchCode: "",
    JobNo: "",
    JobType: "",
    WorkingPeriod: "",
    CommonItem: "",
    OtherDed: "",
    PageCount: "3",
    PdfCount: "",
    JobStatus: "",
    FileName: "",
    Freight: "0.00",
    InvoiceStartTime: "",
    InvoiceResponseTime: "",
    InvoiceStatus: "",
    Client: "",
    IEC: "",
    Insurance: "0.00",
    CountryOfDischarge: "Belgium",
    ExporterName: "GODREJ & BOYCE MFG. CO. LTD.",
    InvoiceNo: "Q1X11000197",
    InvoiceDate: "04/03/2025",
    BuyerName: "SENSY S.A.",
    BuyerOrderNo: "",
    OtherReference: "",
    Commission: "0.00",
    ConsigneeName: "SENSY S.A.",
    ConsigneeAdd1: "ZI DE JUMET - ALLEE CENTRALE",
    ConsigneeAdd2: "BE-6040 JUMET (BELGIUM)",
    ConsigneeAdd3: "CHARLEROI BELGIUM",
    ConsigneeAdd4: "",
    TermsOfPayment: "FREE OF COST",
    PaymentPeriod: "",
    PdfClientName: "",
    PortOfOrgin: "",
    PortOfShipment: "Mumbai Air Cargo",
    PortOfDischarge: "BRUSSELS AIR PORT",
    PortOfFinalDestination: "",
    SchemeCode: "",
    CartonNo: "1",
    OrderNo: "QOE000120/1600",
    KimballNo: "",
    QtyCode: "ECH",
    CountryOfOrigin: "BELGIUM",
    CountryOfShipment: "INDIA",
    Currency: "EUR",
    Discount: "",
    Terms: "DDP",
    InvoiceValue: "2010.00",
    GarmentsIGSTPercentage: "",
    HangerIGSTPercentage: "ZERO",
    TotalGrossWeight: "1.750",
    TotalNetWeight: "1.000",
    TotalCarton: "",
    TotalCBM: "",
    NotifyPartyName: "SENSY S.A.",
    NotifyAddress1: "ZI DE JUMET - ALLEE CENTRALE",
    NotifyAddress2: "BE-6040 JUMET (BELGIUM)",
    NotifyAddress3: "CHARLEROI BELGIUM",
    NotifyAddress4: "",
    invoiceItems: [],
    multiTable: [
      {},
      {
        "Item Details": [
          {
            ItemSlNo: "1",
            ItemDesc:
              "QDEP0004746141500PA04120 ES Underwater load Pin along ES Underwater load Pin Make: SENSY, Model: 5050  -FORC000300 Identification Mark: GDJ-2025-01 [UNDERWATER LOAD PIN 5050  FORC000300QDEP0004746141500PA04120] [COUNTRY OF ORIGIN: BELGIUM] THE ABOVE CONSIGNMENT WAS IMPORTED VIDE: BILL OF ENTRY NO.8924972 DT:24.11.2023 IMPORT INVOICE NO.700002808 DT:10.11.2023 DIM: 230X165X90 MM",
            Quantity: "1.000",
            Rate: "2010.000",
            Amount: "2010.000",
            InfoQty: "",
            InfoUnitPrice: "",
            ExtraItemDesc: "",
            ExtraQuantity: "",
            HSNCode: "90318000",
            IGSTAmount: "ZERO",
            ItemCountry: "BELGIUM",
            ItemQTYCode: "ECH",
            NetWeight: "1",
            TaxableAmount: "2010.00",
            itemSlNo: 1,
          },
        ],
      },
    ],
    referenceNumber: "File8cfbfbc9c85000ca3d9e417fc6ffec49",
    fileName:
      "/home/ubuntu/new_ssd/publicfolder/liberty-fs/File8cfbfbc9c85000ca3d9e417fc6ffec49_GODREJ-1_invoice_Merged.csv",
    orgId: "5c495dbfffa2a85b2c19a77f",
    userId: ObjectId("67ed114950023d3c8c0ef91d"),
    subscriberId: ObjectId("5beaabd82ac6767c86dc311c"),
    createdAt: datetime.datetime(2025, 7, 18, 16, 38, 6, 4368),
    updatedAt: datetime.datetime(2025, 7, 18, 16, 38, 6, 4374),
    isTmp: False,
    ocrConfidence: [],
    Status: "Pending",
    Invoice_Status: "InProgress",
    filePath:
      "/home/ubuntu/new_ssd/publicfolder/liberty-fs/aiqod-dev/File8cfbfbc9c85000ca3d9e417fc6ffec49_GODREJ.pdf",
    file_name: "GODREJ.pdf",
  },
];
