[
  {
    "Invoice Details": [
      {
        InvoiceSlNo: "1",
        InvoiceNo: "13931398",
        InvoiceDate: "01-MAR-2025",
        QtyCode: "EA",
        Currency: "USD",
        Terms: "FCA",
        TermsofPayment: "NET",
        InvoiceValue: "240.80",
        SupplierName: "ARROW ELECTRONICS ASIA (S) PTE. LTD.",
        SupplierAdd1: "1 Tai Seng Avenue, #07-11/12 & 13,",
        SupplierAdd2: "Tai Seng Exchange (Tower A)",
        SupplierAdd3: "Singapore,SG,New Territories",
        SupplierAdd4: "536464 Singapore",
      },
      {
        InvoiceSlNo: "2",
        InvoiceNo: "13931399",
        InvoiceDate: "28-FEB-2025",
        QtyCode: "EA",
        Currency: "USD",
        Terms: "FCA",
        TermsofPayment: "NET",
        InvoiceValue: "13927.68",
        SupplierName: "ARROW ELECTRONICS ASIA (S) PTE. LTD.",
        SupplierAdd1: "1 Tai Seng Avenue, #07-11/12 & 13,",
        SupplierAdd2: "Tai Seng Exchange (Tower A).",
        SupplierAdd3: "Singapore,SG,New Territories",
        SupplierAdd4: "536464 Singapore",
      },
      {
        InvoiceSlNo: "3",
        InvoiceNo: "13935945",
        InvoiceDate: "03-MAR-2025",
        QtyCode: "EA",
        Currency: "USD",
        Terms: "FCA",
        TermsofPayment: "NET",
        InvoiceValue: "3246.24",
        SupplierName: "ARROW ELECTRONICS ASIA (S) PTE. LTD.",
        SupplierAdd1: "1 Tai Seng Avenue, #07-11/i2 & 13,",
        SupplierAdd2: "Tai Seng Exchange (Tower A)",
        SupplierAdd3: "Singapore,SG,New Territories",
        SupplierAdd4: "536464 singapore",
      },
      {
        InvoiceSlNo: "4",
        InvoiceNo: "13935947",
        InvoiceDate: "03-MAR-2025",
        QtyCode: "EA",
        Currency: "USD",
        Terms: "FCA",
        TermsofPayment: "NET",
        InvoiceValue: "801.13",
        SupplierName: "ARROW ELECTRONICS ASIA (S) PTE. LTD.",
        SupplierAdd1: "1 Tai Seng Avenue, #07-11/12 & 13,",
        SupplierAdd2: "Tai Seng Exchange (Tower A)",
        SupplierAdd3: "Singapore,SG,New Territories",
        SupplierAdd4: "536464 Singapore",
      },
    ],
    "Item Details": [
      {
        InvoiceSlNo: "1",
        itemSlNo: 1,
        ItemDesc: "Diode Rectifier Bridge Single 600V 6A 4-PinCase GBU",
        Quantity: "1000",
        Rate: "0.24080",
        Amount: "240.80",
        PartNo: "",
        PONumber: "4201150489",
        ItemNETWEIGHT: "",
        ItemHSCODE: "8541100080",
        ItemCountry: "CN",
      },
      {
        InvoiceSlNo: "2",
        itemSlNo: 1,
        ItemDesc:
          "Telecom Transformer 2(1CT:1CT) 1.5Ohm Prim. DCR 1.50hm Sec. DCR 16 Terminal Gull",
        Quantity: "7200",
        Rate: "0.24960",
        Amount: "1797.12",
        PartNo: "",
        PONumber: "4201049307",
        ItemNETWEIGHT: "",
        ItemHSCODE: "8536.90.10",
        ItemCountry: "CN",
      },
      {
        InvoiceSlNo: "2",
        itemSlNo: 2,
        ItemDesc:
          "Telecom Transformer 2(1CT:1CT) 1.50hm Prim. DCR 1.50hm Sec. DCR 16 Terminal Gull",
        Quantity: "28200",
        Rate: "0.24960",
        Amount: "7038.72",
        PartNo: "",
        PONumber: "4201049307",
        ItemNETWEIGHT: "",
        ItemHSCODE: "8536.90.10",
        ItemCountry: "CN",
      },
      {
        InvoiceSlNo: "2",
        itemSlNo: 3,
        ItemDesc:
          "Telecom Transformer 2(1CT:1CT) 1.5Ohm Prim. DCR 1.5Ohm Sec. DCR 16 Terminal Gull",
        Quantity: "20400",
        Rate: "0.24960",
        Amount: "5091.84",
        PartNo: "",
        PONumber: "4201049307",
        ItemNETWEIGHT: "",
        ItemHSCODE: "8536.90.10",
        ItemCountry: "CN",
      },
      {
        InvoiceSlNo: "3",
        itemSlNo: 1,
        ItemDesc: "DSP Fixed-Point 16bit 300MHz 208-Pin CSP-BGA Tray",
        Quantity: "389",
        Rate: "8.34510",
        Amount: "3246.24",
        PartNo: "",
        PONumber: "4201110888",
        ItemNETWEIGHT: "",
        ItemHSCODE: "8542310001",
        ItemCountry: "KR",
      },
      {
        InvoiceSlNo: "4",
        itemSlNo: 1,
        ItemDesc: "DSP Fixed-Point 16bit 300MHz 208-Pin CSP-BGA Tray",
        Quantity: "96",
        Rate: "8.34510",
        Amount: "801.13",
        PartNo: "",
        PONumber: "4201110888",
        ItemNETWEIGHT: "",
        ItemHSCODE: "8542310001",
        ItemCountry: "KR",
      },
    ],
  },
];
