[
  {
    Branch: "Acc, Chennai",
    CompanyID: None,
    CountryOfShipment: "",
    CountryOfOrigin: "",
    CustomHouse: None,
    IEC: None,
    ImporterName: "GODREJ & BOYCE MFG CO LTD",
    ImporterAdd1: "GALA NO. H10 TC AI DHARA.",
    ImporterAdd2: "MUMBAI-NASH IGHWAY (NH3),BOROLI (KUKSE)",
    ImporterAdd3: "VILLAGE, BHIWANDI THANE :- 421302",
    ImporterAdd4: "",
    InvoiceResponseTime: "",
    InvoiceStartTime: "",
    JobNo: None,
    JobStatus: "N",
    JobType: "IMP",
    PortOfOrgin: "",
    PortOfShipment: "",
    Invoicestatus: "Success",
    TotalCarton: "4",
    TotalGrossWeight: "699",
    TotalNetWeight: "673",
    TotalMeasurement: "1.77",
    UserID: "c",
    WorkingPeriod: None,
    PdfClientName: "GODREJ",
    invoiceItems: [],
    multiTable: [
      {
        InvoiceDetails: [
          {
            InvoiceSLNo: 1,
            InvoiceNo: "SP20250269",
            InvoiceDate: "MAR.20,2025",
            QtyCode: "PCS",
            Currency: "USD",
            Terms: None,
            TermsofPayment: None,
            InvoiceValue: "3,033.99",
            SupplierName: "NOBLELIFT INTELLIGENT EQUIPMENT CO.,LTD.",
            SupplierAdd1: "NO.528 CHANGZHOU ROAD,",
            SupplierAdd2: "TAIHU SUB-DISTRICT,",
            SupplierAdd3: "CHANGXING",
            SupplierAdd4: "ZHEJIANG 313100 CHINA.",
          },
        ],
      },
      {
        "Item Details": [
          {
            InvoiceSlNo: 1,
            itemSlNo: 1,
            ItemDesc: "PTE15N,#508098520001 brush holder",
            Quantity: "4",
            Rate: "3.22",
            Amount: "12.88",
            PartNo: None,
            PONumber: "",
            ItemNETWEIGHT: None,
            ItemHSCODE: "",
            ItemCountry: "",
          },
          {
            InvoiceSlNo: 1,
            itemSlNo: 2,
            ItemDesc: "PTE15N,#502317020000 connecting plate",
            Quantity: "10",
            Rate: "1.12",
            Amount: "11.20",
            PartNo: None,
            PONumber: "",
            ItemNETWEIGHT: None,
            ItemHSCODE: "",
            ItemCountry: "",
          },
          {
            InvoiceSlNo: 1,
            itemSlNo: 3,
            ItemDesc: "RT15DP,#920200400056 proximity switch",
            Quantity: "1",
            Rate: "4.19",
            Amount: "4.19",
            PartNo: None,
            PONumber: "",
            ItemNETWEIGHT: None,
            ItemHSCODE: "",
            ItemCountry: "",
          },
          {
            InvoiceSlNo: 1,
            itemSlNo: 4,
            ItemDesc: "RT15DP,#214533510002 proximity switch Speed Limit",
            Quantity: "1",
            Rate: "14.54",
            Amount: "14.54",
            PartNo: None,
            PONumber: "",
            ItemNETWEIGHT: None,
            ItemHSCODE: "",
            ItemCountry: "",
          },
          {
            InvoiceSlNo: 1,
            itemSlNo: 5,
            ItemDesc: "PSB12,#1000114017 left button",
            Quantity: "1",
            Rate: "4.88",
            Amount: "4.88",
            PartNo: None,
            PONumber: "",
            ItemNETWEIGHT: None,
            ItemHSCODE: "",
            ItemCountry: "",
          },
          {
            InvoiceSlNo: 1,
            itemSlNo: 6,
            ItemDesc: "PSB12,#9000008519 key",
            Quantity: "1",
            Rate: "0.55",
            Amount: "0.55",
            PartNo: None,
            PONumber: "",
            ItemNETWEIGHT: None,
            ItemHSCODE: "",
            ItemCountry: "",
          },
          {
            InvoiceSlNo: 1,
            itemSlNo: 7,
            ItemDesc: "PSB12,#9000008327 switch NBN5-F7-E5",
            Quantity: "1",
            Rate: "14.21",
            Amount: "14.21",
            PartNo: None,
            PONumber: "",
            ItemNETWEIGHT: None,
            ItemHSCODE: "",
            ItemCountry: "",
          },
          {
            InvoiceSlNo: 1,
            itemSlNo: 8,
            ItemDesc: "PSB12,#1000114015 horn button",
            Quantity: "1",
            Rate: "1.05",
            Amount: "1.05",
            PartNo: None,
            PONumber: "",
            ItemNETWEIGHT: None,
            ItemHSCODE: "",
            ItemCountry: "",
          },
          {
            InvoiceSlNo: 1,
            itemSlNo: 9,
            ItemDesc: "PSB12,#9000008332 magnetic switch-HWK2",
            Quantity: "1",
            Rate: "5.37",
            Amount: "5.37",
            PartNo: None,
            PONumber: "",
            ItemNETWEIGHT: None,
            ItemHSCODE: "",
            ItemCountry: "",
          },
          {
            InvoiceSlNo: 1,
            itemSlNo: 10,
            ItemDesc: "PSB12,#9000008846 brake",
            Quantity: "1",
            Rate: "82.62",
            Amount: "82.62",
            PartNo: None,
            PONumber: "",
            ItemNETWEIGHT: None,
            ItemHSCODE: "",
            ItemCountry: "",
          },
          {
            InvoiceSlNo: 1,
            itemSlNo: 11,
            ItemDesc: "PSB12,#9000008858 internal gear",
            Quantity: "1",
            Rate: "137.78",
            Amount: "137.78",
            PartNo: None,
            PONumber: "",
            ItemNETWEIGHT: None,
            ItemHSCODE: "",
            ItemCountry: "",
          },
          {
            InvoiceSlNo: 1,
            itemSlNo: 12,
            ItemDesc: "PTE15N,#508098520018 belly seat",
            Quantity: "2",
            Rate: "0.52",
            Amount: "1.04",
            PartNo: None,
            PONumber: "",
            ItemNETWEIGHT: None,
            ItemHSCODE: "",
            ItemCountry: "",
          },
          {
            InvoiceSlNo: 1,
            itemSlNo: 13,
            ItemDesc: "AC,#315 bearing",
            Quantity: "5",
            Rate: "3.23",
            Amount: "16.15",
            PartNo: None,
            PONumber: "",
            ItemNETWEIGHT: None,
            ItemHSCODE: "",
            ItemCountry: "",
          },
          {
            InvoiceSlNo: 1,
            itemSlNo: 14,
            ItemDesc: "AC,#328 piston rod",
            Quantity: "5",
            Rate: "6.75",
            Amount: "33.75",
            PartNo: None,
            PONumber: "",
            ItemNETWEIGHT: None,
            ItemHSCODE: "",
            ItemCountry: "",
          },
          {
            InvoiceSlNo: 1,
            itemSlNo: 15,
            ItemDesc: "PTE15N,#508098520001 brush holder",
            Quantity: "2",
            Rate: "3.22",
            Amount: "6.44",
            PartNo: None,
            PONumber: "",
            ItemNETWEIGHT: None,
            ItemHSCODE: "",
            ItemCountry: "",
          },
          {
            InvoiceSlNo: 1,
            itemSlNo: 16,
            ItemDesc: "PSB12:#0000027001 bearing 6204",
            Quantity: "6",
            Rate: "0.98",
            Amount: "5.88",
            PartNo: None,
            PONumber: "",
            ItemNETWEIGHT: None,
            ItemHSCODE: "",
            ItemCountry: "",
          },
          {
            InvoiceSlNo: 1,
            itemSlNo: 17,
            ItemDesc: "PTE15N,#502317020000 connecting plate",
            Quantity: "4",
            Rate: "1.12",
            Amount: "4.48",
            PartNo: None,
            PONumber: "",
            ItemNETWEIGHT: None,
            ItemHSCODE: "",
            ItemCountry: "",
          },
          {
            InvoiceSlNo: 1,
            itemSlNo: 18,
            ItemDesc: "PTE15N:#502398510015 small wheel assy",
            Quantity: "4",
            Rate: "3.54",
            Amount: "14.16",
            PartNo: None,
            PONumber: "",
            ItemNETWEIGHT: None,
            ItemHSCODE: "",
            ItemCountry: "",
          },
          {
            InvoiceSlNo: 1,
            itemSlNo: 19,
            ItemDesc: "PTE15N:#920200400056 proximity switch",
            Quantity: "1",
            Rate: "4.19",
            Amount: "4.19",
            PartNo: None,
            PONumber: "",
            ItemNETWEIGHT: None,
            ItemHSCODE: "",
            ItemCountry: "",
          },
          {
            InvoiceSlNo: 1,
            itemSlNo: 20,
            ItemDesc: "DF,#DF20-04 load roller assy single type",
            Quantity: "2",
            Rate: "10.12",
            Amount: "20.24",
            PartNo: None,
            PONumber: "",
            ItemNETWEIGHT: None,
            ItemHSCODE: "",
            ItemCountry: "",
          },
          {
            InvoiceSlNo: 1,
            itemSlNo: 21,
            ItemDesc: "DF,#DF20-05 load roller assy tandem type",
            Quantity: "4",
            Rate: "9.11",
            Amount: "36.44",
            PartNo: None,
            PONumber: "",
            ItemNETWEIGHT: None,
            ItemHSCODE: "",
            ItemCountry: "",
          },
          {
            InvoiceSlNo: 1,
            itemSlNo: 22,
            ItemDesc: "DF,#DF20-08 bracket assy",
            Quantity: "1",
            Rate: "4.46",
            Amount: "4.46",
            PartNo: None,
            PONumber: "",
            ItemNETWEIGHT: None,
            ItemHSCODE: "",
            ItemCountry: "",
          },
          {
            InvoiceSlNo: 1,
            itemSlNo: 23,
            ItemDesc: "FE4P50Q,#256513011001 rim assembly 7.50V-15",
            Quantity: "2",
            Rate: "82.57",
            Amount: "165.14",
            PartNo: None,
            PONumber: "",
            ItemNETWEIGHT: None,
            ItemHSCODE: "",
            ItemCountry: "",
          },
          {
            InvoiceSlNo: 1,
            itemSlNo: 24,
            ItemDesc: "FE4P50Q,#256615511001 rim assembly 6.50F-10",
            Quantity: "2",
            Rate: "51.15",
            Amount: "102.30",
            PartNo: None,
            PONumber: "",
            ItemNETWEIGHT: None,
            ItemHSCODE: "",
            ItemCountry: "",
          },
          {
            InvoiceSlNo: 1,
            itemSlNo: 25,
            ItemDesc: "FE4P50Q,#256513010001 drive wheel assembly 250-15",
            Quantity: "",
            Rate: "273.17",
            Amount: "546.34",
            PartNo: None,
            PONumber: "",
            ItemNETWEIGHT: None,
            ItemHSCODE: "",
            ItemCountry: "",
          },
          {
            InvoiceSlNo: 1,
            itemSlNo: 26,
            ItemDesc: "FE4P50Q,#256513011010 tire 250-15 solid front tyre",
            Quantity: "",
            Rate: "326.26",
            Amount: "",
            PartNo: None,
            PONumber: "",
            ItemNETWEIGHT: None,
            ItemHSCODE: "",
            ItemCountry: "",
          },
          {
            InvoiceSlNo: 1,
            itemSlNo: 27,
            ItemDesc: "FE4P50Q,#255013010003 tire 23*9-10 solid rear tyre",
            Quantity: "",
            Rate: "169.21",
            Amount: "338.42",
            PartNo: None,
            PONumber: "",
            ItemNETWEIGHT: None,
            ItemHSCODE: "",
            ItemCountry: "",
          },
          {
            InvoiceSlNo: 1,
            itemSlNo: 28,
            ItemDesc: "FE4P50Q,#256615510001 rear tire assembly 23*9-10",
            Quantity: "2",
            Rate: "169.21",
            Amount: "338.42",
            PartNo: None,
            PONumber: "",
            ItemNETWEIGHT: None,
            ItemHSCODE: "",
            ItemCountry: "",
          },
          {
            InvoiceSlNo: 1,
            itemSlNo: 29,
            ItemDesc: "PTE15N,#508011010002 Welding Fixed Shaft",
            Quantity: "1",
            Rate: "1.13",
            Amount: "1.13",
            PartNo: None,
            PONumber: "",
            ItemNETWEIGHT: None,
            ItemHSCODE: "",
            ItemCountry: "",
          },
          {
            InvoiceSlNo: 1,
            itemSlNo: 30,
            ItemDesc: "PTE15N,#508011020005 Holder",
            Quantity: "1",
            Rate: "0.36",
            Amount: "0.36",
            PartNo: None,
            PONumber: "",
            ItemNETWEIGHT: None,
            ItemHSCODE: "",
            ItemCountry: "",
          },
          {
            InvoiceSlNo: 1,
            itemSlNo: 31,
            ItemDesc: "PTE15N#910401300006 Shaft Circlip",
            Quantity: "1",
            Rate: "0.01",
            Amount: "0.01",
            PartNo: None,
            PONumber: "",
            ItemNETWEIGHT: None,
            ItemHSCODE: "",
            ItemCountry: "",
          },
          {
            InvoiceSlNo: 1,
            itemSlNo: 32,
            ItemDesc: "PSB12,#2000300004, Filter",
            Quantity: "3",
            Rate: "12.39",
            Amount: "37.17",
            PartNo: None,
            PONumber: "",
            ItemNETWEIGHT: None,
            ItemHSCODE: "",
            ItemCountry: "",
          },
          {
            InvoiceSlNo: 1,
            itemSlNo: 33,
            ItemDesc: "AC,#B212 Pushing Rod Type",
            Quantity: "2",
            Rate: "7.14",
            Amount: "14.28",
            PartNo: None,
            PONumber: "",
            ItemNETWEIGHT: None,
            ItemHSCODE: "",
            ItemCountry: "",
          },
          {
            InvoiceSlNo: 1,
            itemSlNo: 34,
            ItemDesc: "AC,#320 Elastic",
            Quantity: "10",
            Rate: "0.14",
            Amount: "1.40",
            PartNo: None,
            PONumber: "",
            ItemNETWEIGHT: None,
            ItemHSCODE: "",
            ItemCountry: "",
          },
          {
            InvoiceSlNo: 1,
            itemSlNo: 35,
            ItemDesc: "RT15DP,#921100100145 Camera",
            Quantity: "1",
            Rate: "216.60",
            Amount: "216.60",
            PartNo: None,
            PONumber: "",
            ItemNETWEIGHT: None,
            ItemHSCODE: "",
            ItemCountry: "",
          },
          {
            InvoiceSlNo: 1,
            itemSlNo: 36,
            ItemDesc: "FE4P50Q,#256625011002 Multiple valve (triple mast)",
            Quantity: "1",
            Rate: "182.40",
            Amount: "182.40",
            PartNo: None,
            PONumber: "",
            ItemNETWEIGHT: None,
            ItemHSCODE: "",
            ItemCountry: "",
          },
          {
            InvoiceSlNo: 1,
            itemSlNo: 37,
            ItemDesc: "RT15DP,#214553020143 Spring",
            Quantity: "2",
            Rate: "0.50",
            Amount: "1.00",
            PartNo: None,
            PONumber: "",
            ItemNETWEIGHT: None,
            ItemHSCODE: "",
            ItemCountry: "",
          },
        ],
      },
    ],
  },
];
