 {
   type: 'choice',
   response: 'Provide value for itemName using these options.',
   response_type: 'select',
   count: 6268,
   options: [
     'Bookshelf',
     'Nap mats',
     'Art easel',
     'Safety scissors',
     'Picture books',
     'First aid kit',
     'Cleaning supplies kit',
     'Tricycles',
     'Sandbox toys',
     'Soft toys',
     'Shoes rack',
     'Welcome signage',
     'Table',
     "Teacher's chair",
     'Storage cabinet',
     'Rug',
     'Alphabet blocks',
     'Number puzzle set',
     'Learning posters',
     'Parker pen',
     'Printer',
     'Dustbin',
     'Plates and cups',
     'Name tag set',
     'Hand sanitizer dispensers',
     "Teacher's desk",
     'Bulletin board',
     'Cubbies',
     'Watercolor paint set',
     'Files and folders',
     'Attendance register',
     'Projector',
     'Speaker system',
     'Water dispenser',
     'Slide',
     'Puppet set',
     'Wall clock',
     'Chair',
     'Whiteboard',
     'Bean bag',
     'Crayons set',
     'Craft paper pack',
     'Glue sticks',
     'Flashcards',
     'Storybooks collection',
     'A4 printing paper',
     'Computer',
     'Mini fridge',
     'Microwave',
     'Curriculum books'
   ],
   summary: 'this is the conversation history:  and this is summary: Based on customer information field extracted till now, Response: {} and waiting for itemName value from customer .'
 }
