[
  {
  Branch: 'Acc, Chennai',
  CompanyID: null,
  CountryOfOrigin: null,
  CountryOfShipment: null,
  CustomHouse: null,
  IEC: null,
  ImporterAdd1: 'SVEANAGAR MUMBAI PUNE ROAD',
  ImporterAdd2: '411012 PUNE',
  ImporterAdd3: 'India',
  ImporterAdd4: null,
  ImporterName: 'Atlas Copco (India) Private limited',
  InvoiceResponseTime: null,
  InvoiceStartTime: null,
  Invoicestatus: 'Success',
  JobNo: null,
  JobStatus: 'N',
  JobType: 'IMP',
  PdfClientName: 'ATLES COPCO',
  PortOfOrgin: '',
  PortOfShipment: '',
  TotalCarton: '1',
  TotalGrossWeight: '',
  TotalMeasurement: '',
  TotalNetWeight: '',
  UserID: 'c',
  WorkingPeriod: null
},
  {
  Currency: 'EUR',
  InvoiceDate: '2025-03-25',
  InvoiceNo: '9002164731',
  InvoiceSLNo: 1,
  InvoiceValue: '50.929,94',
  QtyCode: 'PC',
  SupplierAdd1: 'Industrielaan 40,',
  SupplierAdd2: '3730 Bilzen-Hoeselt',
  SupplierAdd3: 'Belgium',
  SupplierAdd4: '',
  SupplierName: 'Power Tools Distribution N.V.',
  Terms: 'CIP'
},
{
  Amount: '2.463,81',
  ExtraItemDesc: '25B77473',
  InvoiceSlNo: '1',
  ItemCountry: '',
  ItemDesc: 'ERP20 6151661990\n6151661990',
  ItemHSCODE: '84672985',
  ItemNETWEIGHT: null,
  PONumber: '',
  PartNo: null,
  Quantity: '1',
  Rate: '2.463,810',
  itemSlNo: 1
}
];
