[
  {
    Branch: "Acc, Chennai",
    CompanyID: null,
    CountryOfOrigin: "",
    CountryOfShipment: "",
    CustomHouse: null,
    FileName: "",
    IEC: null,
    ImporterAdd1: "SVEANAGAR MUMBAI PUNE ROAD",
    ImporterAdd2: "411012 PUNE",
    ImporterAdd3: "India",
    ImporterAdd4: "",
    ImporterName: "Atlas Copco (India) Private limited",
    InvoiceResponseTime: "01/04/2025 19:05:31",
    InvoiceStartTime: "29-07-2024",
    JobNo: null,
    JobStatus: "N",
    JobType: "IMP",
    PageCount: "22",
    PdfClientName: "ATLES COPCO",
    PdfCount: "1",
    PortOfOrigin: "",
    PortOfShipment: "",
    Status: "Success",
    TotalCarton: "1",
    TotalGrossWeight: "",
    TotalMeasurement: "",
    TotalNetWeight: "",
    UserID: "c",
    WorkingPeriod: null,
  },
  {
    Currency: "EUR",
    InvoiceDate: "2025-03-25",
    InvoiceNo: "9002164731",
    InvoiceSlNo: 1,
    InvoiceValue: "50.929,94",
    QtyCode: "pcs",
    SupplierAdd1: "Industrielaan 40,",
    SupplierAdd2: "3730 Bilzen-Hoeselt",
    SupplierAdd3: "Belgium",
    SupplierAdd4: "",
    SupplierName: "Power Tools Distribution N.V.",
    Terms: "FCA",
    TermsofPayment: "",
  },
  {
    Amount: "2 463, 81",
    ExtraItemDesc: "25B77473",
    InvoiceSlNo: "1",
    ItemCountry: "",
    ItemDesc: "ERP20 6151661990",
    ItemHSCODE: "84672985",
    ItemNETWEIGHT: null,
    ItemSlNo: "1",
    PONumber: "",
    PartNo: null,
    Quantity: "1",
    Rate: "2 463, 810",
  },
];
