[
  {
  Branch: 'Acc, Chennai',
  CompanyID: null,
  CountryOfOrigin: '',
  CountryOfShipment: '',
  CustomHouse: null,
  FileName: '',
  IEC: null,
  ImporterAdd1: 'LTD (IPDC - AC1) PLOT NO A-1',
  ImporterAdd2: 'MIDC PHALTAN LONAND PHALTAN RD',
  ImporterAdd3: 'VILLAGE SURAVADI TAL. PHALTAN',
  ImporterAdd4: 'SATARA,415523 INDIA',
  ImporterName: 'CUMMINS TECHNOLOGIES INDIA PVT',
  InvoiceResponseTime: '01/04/2025 19:05:31',
  InvoiceStartTime: '29-07-2024',
  JobNo: null,
  JobStatus: 'N',
  JobType: 'IMP',
  PageCount: '22',
  PdfClientName: 'CUMMINS TECHNOLOGIES',
  PdfCount: '1',
  PortOfOrigin: '',
  PortOfShipment: '',
  Status: 'Success',
  TotalCarton: '',
  TotalGrossWeight: '',
  TotalMeasurement: '',
  TotalNetWeight: '',
  UserID: 'c',
  WorkingPeriod: null
},
 {
  Currency: 'USD',
  InvoiceDate: '18-03-2025',
  InvoiceNo: '11902659',
  InvoiceSlNo: 1,
  InvoiceValue: '203.47',
  QtyCode: 'pcs',
  SupplierAdd1: 'CATENBERGSTRAAT 1',
  SupplierAdd2: '2840 RUMST',
  SupplierAdd3: 'BELGIUM',
  SupplierAdd4: '',
  SupplierName: 'CUMMINS NV',
  Terms: 'FCA',
  TermsofPayment: ''
},
 {
  Amount: '39.00',
  InvoiceSlNo: '1',
  ItemCountry: '',
  ItemDesc: 'SEAL,FERRULE 325429400',
  ItemHSCODE: '4016930090',
  ItemNETWEIGHT: null,
  ItemSlNo: '1',
  PONumber: '',
  PartNo: null,
  Quantity: '4',
  Rate: '9.75'
},
];
