[
{
  Branch: 'Acc, Chennai',
  CompanyID: null,
  CountryOfOrigin: null,
  CountryOfShipment: null,
  CustomHouse: null,
  IEC: null,
  ImporterAdd1: 'KOTHRUD',
  ImporterAdd2: 'Pune',
  ImporterAdd3: 'Maharashtra India',
  ImporterAdd4: '411038',
  ImporterName: 'CUMMINS INDIA LTD (BC085)',
  InvoiceResponseTime: null,
  InvoiceStartTime: null,
  Invoicestatus: 'Success',
  JobNo: null,
  JobStatus: 'N',
  JobType: 'IMP',
  PdfClientName: 'CUMMINS INDIA LIMITED',
  PortOfOrgin: '',
  PortOfShipment: '',
  TotalCarton: '5',
  TotalGrossWeight: '1565',
  TotalMeasurement: '',
  TotalNetWeight: '1492',
  UserID: 'c',
  WorkingPeriod: null
},
  {
  Currency: 'USD',
  InvoiceDate: '2025-03-21',
  InvoiceNo: '60400000009120',
  InvoiceSLNo: 1,
  InvoiceValue: '107,932.48',
  QtyCode: null,
  SupplierAdd1: '500 Jackson Street',
  SupplierAdd2: 'Columbus',
  SupplierAdd3: 'United States',
  SupplierAdd4: '47201',
  SupplierName: 'Cummins Inc.-Division-JV Kitting US (BC604)',
  Terms: 'FCA',
  TermsofPayment: ''
},
  {
  Amount: '765.60',
  InvoiceSlNo: '1',
  ItemCountry: '',
  ItemDesc: 'SEAL,THERMOSTAT 8500019033 1136 EAR99,NLR 26688441',
  ItemHSCODE: '4016935050',
  ItemNETWEIGHT: null,
  PONumber: '',
  PartNo: '186780',
  Quantity: '480',
  Rate: '1.595',
  itemSlNo: 1
},
];
