[
  {
    Branch: "Acc, Chennai",
    CompanyID: null,
    CountryOfOrigin: "",
    CountryOfShipment: "",
    CustomHouse: null,
    FileName: "KEP US INVOICE",
    IEC: null,
    ImporterAdd1: "KOTHRUD",
    ImporterAdd2: "Pune",
    ImporterAdd3: "Maharashtra India",
    ImporterAdd4: "411038",
    ImporterName: "CUMMINS INDIA LIMITED",
    InvoiceResponseTime: "01/04/2025 19:05:31",
    InvoiceStartTime: "29-07-2024",
    JobNo: null,
    JobStatus: "N",
    JobType: "IMP",
    PageCount: 9,
    PdfClientName: "CUMMINS INDIA LIMITED",
    PdfCount: 1,
    PortOfOrigin: "",
    PortOfShipment: "",
    Status: "Success",
    TotalCarton: "4",
    TotalGrossWeight: "1565",
    TotalMeasurement: "",
    TotalNetWeight: "",
    UserID: "c",
    WorkingPeriod: null,
  },
  {
    Currency: "US",
    InvoiceDate: "21-mAR-25",
    InvoiceNo: "60400000009120",
    InvoiceSlNo: 1,
    InvoiceValue: "107,932.48",
    QtyCode: "PCS",
    SupplierAdd1: "Kitting US (BC604)",
    SupplierAdd2: "500 Jackson Street",
    SupplierAdd3: "Columbus",
    SupplierAdd4: "United States 47201",
    SupplierName: "Cummins Inc-Division-,JV",
    Terms: "FOB",
    TermsofPayment: "",
  },
  {
    Amount: "765.60",
    InvoiceSlNo: 1,
    ItemCountry: "",
    ItemDesc: "SEAL,THERMOSTAT",
    ItemHSCODE: "4016935050",
    ItemNETWEIGHT: null,
    ItemSlNo: "1",
    PONumber: "",
    PartNo: null,
    Quantity: "480",
    Rate: "1,595",
  },
];
