[
  {
    Branch: "Acc, Chennai",
    CompanyID: null,
    CountryOfOrigin: null,
    CountryOfShipment: null,
    CustomHouse: null,
    IEC: null,
    ImporterAdd1: "LTD (IPDC - AC1) PLOT NO A-1",
    ImporterAdd2: "MIDC PHALTAN LONAND PHALTAN RD",
    ImporterAdd3: "VILLAGE SURAVADI TAL. PHALTAN",
    ImporterAdd4: "SATARA, . 415523 INDIA",
    ImporterName: "CUMMINS TECHNOLOGIES INDIA PVT",
    InvoiceResponseTime: null,
    InvoiceStartTime: null,
    Invoicestatus: "Success",
    JobNo: null,
    JobStatus: "N",
    JobType: "IMP",
    PdfClientName: "CUMMINS TECHNOLOGIES",
    PortOfOrgin: null,
    PortOfShipment: null,
    TotalCarton: "",
    TotalGrossWeight: "",
    TotalMeasurement: "",
    TotalNetWeight: "",
    UserID: "c",
    WorkingPeriod: null,
  },
  {
    Currency: "USD",
    InvoiceDate: "18-03-2025",
    InvoiceNo: "11902659",
    InvoiceSLNo: 1,
    InvoiceValue: "203.47",
    QtyCode: "pcs",
    SupplierAdd1: "CATENBERGSTRAAT 1",
    SupplierAdd2: "2840 RUMST",
    SupplierAdd3: "BELGIUM",
    SupplierAdd4: "",
    SupplierName: "CUMMINS NV",
    Terms: "FCA",
    TermsofPayment: "",
  },
  {
    Amount: "39.00",
    InvoiceSlNo: "1",
    ItemCountry: null,
    ItemDesc: "SEAL,FERRULE 325429400",
    ItemHSCODE: "4016930090",
    ItemNETWEIGHT: null,
    PONumber: "",
    PartNo: null,
    Quantity: "4",
    Rate: "9.75",
    itemSlNo: "1",
  },
];
