[
  {
    Branch: "Acc, Chennai",
    CompanyID: null,
    CountryOfOrigin: null,
    CountryOfShipment: null,
    CustomHouse: null,
    IEC: null,
    ImporterAdd1: "Clo Madhvi Stones,",
    ImporterAdd2: "Khasra No 868/835, 869/809, 870/762",
    ImporterAdd3: "27 Bheelo ka Bedla,Near Amberi Brid",
    ImporterAdd4: "Udaipur, Rajasthan - 313011 RJ IN",
    ImporterName: "Epiroc Mining India Private Limited",
    InvoiceResponseTime: "",
    InvoiceStartTime: "",
    Invoicestatus: "Success",
    JobNo: null,
    JobStatus: "N",
    JobType: "IMP",
    PdfClientName: "Epiroc Mining",
    PortOfOrgin: "",
    PortOfShipment: "",
    TotalCarton: "4",
    TotalGrossWeight: "",
    TotalMeasurement: "",
    TotalNetWeight: "",
    UserID: "c",
    WorkingPeriod: null,
  },
  {
    Currency: "USD",
    InvoiceDate: "2025-03-27",
    InvoiceNo: "251401935",
    InvoiceSLNo: 1,
    InvoiceValue: "55,721.59",
    QtyCode: "EA",
    SupplierAdd1: "Singapore 608531",
    SupplierAdd2: "Singapore",
    SupplierAdd3: "",
    SupplierAdd4: "",
    SupplierName: "Epiroc Singapore Distribution PTE. LTD.",
    Terms: "CPT",
    TermsofPayment: "Intercompany 2nd Month",
  },
  {
    Amount: "588.60",
    InvoiceSlNo: 1,
    ItemCountry: "US",
    ItemDesc: "BEARING 5535450400 BEARING-CONE",
    ItemHSCODE: "84829900",
    ItemNETWEIGHT: "3.435",
    PONumber: "",
    PartNo: null,
    Quantity: "3.00",
    Rate: "196.20",
    itemSlNo: 1,
  },
];
