[
  {
    Branch: "Acc, Chennai",
    CompanyID: null,
    CountryOfOrigin: "",
    CountryOfShipment: "",
    CustomHouse: null,
    FileName: "251401935__Epiroc Singapore Distribution PTE. LTD. (1)",
    IEC: null,
    ImporterAdd1: "C/o Madhvi Stones,",
    ImporterAdd2: "Khasra No 868/835, 869/809, 870/762",
    ImporterAdd3: "27 Bheelo ka Bedla,Near Amberi Brid",
    ImporterAdd4: "Udaipur, Rajasthan - 313011 RJ IN",
    ImporterName: "Epiroc Mining India Private Limited",
    InvoiceResponseTime: "01/04/2025 19:05:31",
    InvoiceStartTime: "29-07-2024",
    JobNo: null,
    JobStatus: "N",
    JobType: "IMP",
    PageCount: 4,
    PdfClientName: "Epiroc Mining",
    PdfCount: 17,
    PortOfOrigin: "",
    PortOfShipment: "",
    Status: "Success",
    TotalCarton: "4",
    TotalGrossWeight: "",
    TotalMeasurement: "",
    TotalNetWeight: "",
    UserID: "c",
    WorkingPeriod: null,
  },
  {
    Currency: "USD",
    InvoiceDate: "2025-03-27",
    InvoiceNo: "251401935",
    InvoiceSlNo: 1,
    InvoiceValue: "55,721.59",
    QtyCode: "EA",
    SupplierAdd1: "Singapore 608531",
    SupplierAdd2: "Singapore",
    SupplierAdd3: "",
    SupplierAdd4: "",
    SupplierName: "Epiroc Singapore Distribution PTE. LTD.",
    Terms: "CPT",
    TermsofPayment: "",
  },
  {
    Amount: "588.60",
    InvoiceSlNo: 1,
    ItemCountry: "US",
    ItemDesc: "BEARING 5535450400",
    ItemHSCODE: "84829900",
    ItemNETWEIGHT: null,
    ItemSlNo: 1,
    PONumber: "",
    PartNo: null,
    Quantity: "3.00",
    Rate: "196.20",
  },
];
