[
  {
    Branch: "Acc, Chennai",
    CompanyID: null,
    CountryOfOrigin: "",
    CountryOfShipment: "",
    CustomHouse: null,
    FileName: "NOBLELIFT INVOICE",
    IEC: null,
    ImporterAdd1: "GODREJ AND BOYCE MFG CO LTD",
    ImporterAdd2: "MUMBAI-NASHIK HIGHWAY (NH3),",
    ImporterAdd3: "BOROLI (KUKSE)",
    ImporterAdd4: "VILLAGE, BHIWANDI, THANE :- 421302.",
    ImporterName: "GODREJ AND BOYCE MFG CO LTD",
    InvoiceResponseTime: "01/04/2025 19:05:31",
    InvoiceStartTime: "29-07-2024",
    JobNo: null,
    JobStatus: "N",
    JobType: "IMP",
    PageCount: 4,
    PdfClientName: "GODREJ",
    PdfCount: 1,
    PortOfOrigin: "",
    PortOfShipment: "",
    Status: "Success",
    TotalCarton: "4",
    TotalGrossWeight: "699",
    TotalMeasurement: "1.77",
    TotalNetWeight: "673",
    UserID: "c",
    WorkingPeriod: null,
  },
  {
    Currency: "USD",
    InvoiceDate: "MAR.20,2025",
    InvoiceNo: "SP20250269",
    InvoiceSlNo: 1,
    InvoiceValue: "3,033.99",
    QtyCode: "PCS",
    SupplierAdd1: "NO.528 CHANGZHOU ROAD,",
    SupplierAdd2: "TAIHU SUB-DISTRICT,",
    SupplierAdd3: "VILLAGE, BHIWANDI,",
    SupplierAdd4: "ZHEJIANG 313100 CHINA.",
    SupplierName: "NOBLELIFT INTELLIGENT EQUIPMENT CO.,LTD.",
    Terms: "",
    TermsofPayment: "",
  },
  {
    Amount: "12.88",
    InvoiceSlNo: 1,
    ItemCountry: "",
    ItemDesc: "PTE15N,#508098520001 brush holder",
    ItemHSCODE: "",
    ItemNETWEIGHT: null,
    ItemSlNo: 1,
    PONumber: "",
    PartNo: null,
    Quantity: "4",
    Rate: "3.22",
  },
];
