[
  {
    Branch: "Acc, Chennai",
    CompanyID: null,
    CountryOfOrigin: "",
    CountryOfShipment: "",
    CustomHouse: null,
    IEC: null,
    ImporterAdd1: "GODREJ & BOYCE MFG. CO. LTD.",
    ImporterAdd2: "GALA NO. H10 TO H12, SAI DHARA,",
    ImporterAdd3: "MUMBAI-NASHIK HIGHWAY (NH3), BOROLI (KUKSE)",
    ImporterAdd4: "VILLAGE, BHIWANDI, THANE :- 421302.",
    ImporterName: "GODREJ & BOYCE MFG. CO. LTD.",
    InvoiceResponseTime: "",
    InvoiceStartTime: "",
    Invoicestatus: "Success",
    JobNo: null,
    JobStatus: "N",
    JobType: "IMP",
    PdfClientName: "",
    PortOfShipment: "",
    TotalCarton: "4",
    TotalGrossWeight: "699",
    TotalMeasurement: "1.77",
    TotalNetWeight: "673",
    UserID: "c",
    WorkingPeriod: null,
  },
  {
    Currency: "USD",
    InvoiceDate: "MAR.20,2025",
    InvoiceNo: "SP20250269",
    InvoiceSLNo: 1,
    InvoiceValue: "3,033.99",
    QtyCode: "PCS",
    SupplierAdd1: "NO.528 CHANGZHOU ROAD, TAIHU SUB-DISTRICT,",
    SupplierAdd2: "CHANGXING,",
    SupplierAdd3: "ZHEJIANG 313100 CHINA.",
    SupplierAdd4: "",
    SupplierName: "NOBLELIFT INTELLIGENT EQUIPMENT CO.,LTD.",
    Terms: null,
    TermsofPayment: null,
  },
  {
    Amount: "12.88",
    InvoiceSlNo: 1,
    ItemCountry: "",
    ItemDesc: "PTE15N,#508098520001 brush holder",
    ItemHSCODE: "",
    ItemNETWEIGHT: null,
    PONumber: "",
    PartNo: null,
    Quantity: "4",
    Rate: "3.22",
    itemSlNo: 1,
  },
];
