[
  {
    Branch: "Acc, Chennai",
    CompanyID: null,
    CountryOfOrigin: "",
    CountryOfShipment: "",
    CustomHouse: null,
    IEC: null,
    ImporterAdd1: "Gala no. H10 to H12, Sai Dhara",
    ImporterAdd2: "Mumbai-Nashik Highway (NH3),",
    ImporterAdd3: "421302 Thane",
    ImporterAdd4: "Boroli(Kukse) village,Bhiwandi India",
    ImporterName: "Godrej & Boyce Mfg. Co. Ltd.",
    InvoiceResponseTime: "",
    InvoiceStartTime: "",
    Invoicestatus: "Success",
    JobNo: null,
    JobStatus: "N",
    JobType: "IMP",
    PdfClientName: "Godrej & Boyce Mfg. Co Ltd",
    PortOfShipment: "",
    TotalCarton: "3",
    TotalGrossWeight: "527",
    TotalMeasurement: "",
    TotalNetWeight: "407.04",
    UserID: "c",
    WorkingPeriod: null,
  },
  {
    Currency: "EUR",
    InvoiceDate: "21-03-2025",
    InvoiceNo: "V10/11009879",
    InvoiceSLNo: 1,
    InvoiceValue: "857,40",
    QtyCode: "pcs",
    SupplierAdd1: "Central Parts Center",
    SupplierAdd2: "Parsdorfer Str. 3",
    SupplierAdd3: "85652 Pliening",
    SupplierAdd4: "",
    SupplierName: "Crown Gabelstapler GmbH & Co. KG",
    Terms: "FOB",
    TermsofPayment: "",
  },
  {
    Amount: "2,71",
    InvoiceSlNo: "1",
    ItemCountry: "",
    ItemDesc: "125833 Screw Slotted Round Head",
    ItemHSCODE: "",
    ItemNETWEIGHT: null,
    PONumber: "",
    PartNo: null,
    Quantity: "2",
    Rate: "1,36",
    itemSlNo: "1",
  },
];
