[
  {
    Branch: "Acc, Chennai",
    CompanyID: null,
    CountryOfOrigin: "",
    CountryOfShipment: "",
    CustomHouse: null,
    FileName: "",
    IEC: null,
    ImporterAdd1: "Gala no. H10 to H12, Sai Dhara",
    ImporterAdd2: "Mumbai-Nashik Highway (NH3),",
    ImporterAdd3: "421302 Thane",
    ImporterAdd4: "Boroli(Kukse) village,Bhiwandi India",
    ImporterName: "Godrej & Boyce Mfg. Co. Ltd.",
    InvoiceResponseTime: "01/04/2025 19:05:31",
    InvoiceStartTime: "29-07-2024",
    JobNo: null,
    JobStatus: "N",
    JobType: "IMP",
    PageCount: "22",
    PdfClientName: "Godrej & Boyce Mfg. Co Ltd",
    PdfCount: "1",
    PortOfOrigin: "",
    PortOfShipment: "",
    Status: "Success",
    TotalCarton: "4",
    TotalGrossWeight: "1565",
    TotalMeasurement: "",
    TotalNetWeight: "",
    UserID: "c",
    WorkingPeriod: null,
  },
  {
    Currency: "EUR",
    InvoiceDate: "21-03-2025",
    InvoiceNo: "V10/11009879",
    InvoiceSlNo: 1,
    InvoiceValue: "857,40",
    QtyCode: "pcs",
    SupplierAdd1: "Central Parts Center",
    SupplierAdd2: "Parsdorfer Str. 3",
    SupplierAdd3: "85652 Pliening",
    SupplierAdd4: "",
    SupplierName: "Crown Gabelstapler GmbH & Co. KG",
    Terms: "",
    TermsofPayment: "",
  },
  {
    Amount: "2,71",
    InvoiceSlNo: "1",
    ItemCountry: "",
    ItemDesc: "Screw Slotted Round Head 125833",
    ItemHSCODE: "",
    ItemNETWEIGHT: null,
    ItemSlNo: "1",
    PONumber: "",
    PartNo: null,
    Quantity: "2",
    Rate: "1,36",
  },
];
