[
  {
    Branch: "Acc, Chennai",
    CompanyID: null,
    CountryOfOrigin: null,
    CountryOfShipment: null,
    CustomHouse: null,
    IEC: null,
    ImporterAdd1: "C/o Reliance Industries Ltd,",
    ImporterAdd2: "2nd Floor, NO 62/2, RIL Building,",
    ImporterAdd3: "Richmond Road, Bengaluru Urban",
    ImporterAdd4: "560025 BENGALURU INDIA",
    ImporterName: "Reliance Consumer Products Ltd",
    InvoiceResponseTime: null,
    InvoiceStartTime: null,
    Invoicestatus: "Success",
    JobNo: null,
    JobStatus: "N",
    JobType: "IMP",
    PdfClientName: "Reliance",
    PortOfShipment: null,
    TotalCarton: "",
    TotalGrossWeight: "",
    TotalMeasurement: "",
    TotalNetWeight: "",
    UserID: "c",
    WorkingPeriod: null,
  },
  {
    Currency: "EUR",
    InvoiceDate: "28.03.2025",
    InvoiceNo: "94562288",
    InvoiceSLNo: 1,
    InvoiceValue: "185.272,77",
    QtyCode: "PCE",
    SupplierAdd1: "39th Floor Interlink Tower",
    SupplierAdd2: "1858/138 Debaratna Road, Bangna Tai Sub District",
    SupplierAdd3: "Bangna District, Bangkok 10260, Thailand",
    SupplierAdd4: "",
    SupplierName: "KRONES (Thailand) Co., Ltd.",
    Terms: "CIP",
    TermsofPayment: "in advance",
  },
  {
    Amount: "20,00",
    InvoiceSlNo: 1,
    ItemCountry: "JP",
    ItemDesc: "0900815167 O-ring 90x8 EPDM peroxide",
    ItemHSCODE: "401693",
    ItemNETWEIGHT: null,
    PONumber: null,
    PartNo: null,
    Quantity: "1",
    Rate: "20,00",
    itemSlNo: 1,
  },
];
