[
  {
    Branch: "Acc, Chennai",
    CompanyID: null,
    CountryOfOrigin: null,
    CountryOfShipment: null,
    CustomHouse: null,
    FileName: "94562288",
    Freight: null,
    IEC: null,
    ImporterAdd1: "C/O Reliance Industries Ltd,",
    ImporterAdd2: "2nd Floor, NO 62/2, RIL Building,",
    ImporterAdd3: "Richmond Road, Bengaluru Urban",
    ImporterAdd4: "560025 BENGALURU INDIA",
    ImporterName: "Reliance Consumer Products Ltd",
    InvoiceResponseTime: "08/04/2025 10:42:21",
    InvoiceStartTime: "29-07-2024",
    JobNo: null,
    JobStatus: "N",
    JobType: "imp",
    PageCount: 55,
    PdfClientName: "Reliance",
    PdfCount: 1,
    PortOfOrigin: null,
    PortOfShipment: null,
    Status: "Success",
    TotalCarton: "",
    TotalGrossWeight: "",
    TotalMeasurement: "",
    TotalNetWeight: "",
    UserID: "c",
    WorkingPeriod: null,
  },
  {
    Currency: "EUR",
    InvoiceDate: "28.03.2025",
    InvoiceNo: "94562288",
    InvoiceSlNo: 1,
    InvoiceValue: "180,996.79",
    QtyCode: "PCE",
    SupplierAdd1: "39th Floor Interlink Tower",
    SupplierAdd2: "1858/138 Debaratna Road, Bangna Tai Sub District",
    SupplierAdd3: "Bangna District,",
    SupplierAdd4: "Bangkok 10260, Thailand",
    SupplierName: "KRONES (Thailand) Co., Ltd.",
    Terms: "CIP",
    TermsofPayment: null,
  },
  {
    Amount: "20,00",
    InvoiceSlNo: 1,
    ItemCountry: null,
    ItemDesc: "0900815167 O-ring 90x8 EPDM peroxide",
    ItemHSCODE: "401693",
    ItemNETWEIGHT: null,
    ItemSlNo: 1,
    PONumber: null,
    PartNo: null,
    Quantity: "1",
    Rate: "20,00",
  },
];
