[
  {
    Branch: "ACC, Chennai",
    CompanyID: "ERI00001",
    CountryOfOrigin: "CN",
    CountryOfShipment: "CN",
    CustomHouse: "",
    IEC: "0388070005",
    ImporterAdd1: "PLOT NO. L6, VERNA INDUSTRIAL ESTATE,",
    ImporterAdd2: "OPP GOA-MUMBAI HIGHWAY",
    ImporterAdd3: "VERNA",
    ImporterAdd4: "South Goa,Goa 403722 India",
    ImporterName: "SIEMENS LTD",
    InvoiceResponseTime: "",
    InvoiceStartTime: "",
    Invoicestatus: "Success",
    JobNo: "",
    JobStatus: "N",
    JobType: "IMP",
    PdfClientName: "SIEMENS LIMITED",
    PortOfOrgin: "Singapore",
    PortOfShipment: "Singapore",
    TotalCarton: "",
    TotalGrossWeight: "",
    TotalMeasurement: "",
    TotalNetWeight: "",
    UserID: "RTS",
    WorkingPeriod: "null",
  },
  {
    Currency: "USD",
    InvoiceDate: "01-MAR-2025",
    InvoiceNo: "13931398",
    InvoiceSlNo: "1",
    InvoiceValue: "240.80",
    QtyCode: "EA",
    SupplierAdd1: "1 Tai Seng Avenue, #07-11/12 & 13,",
    SupplierAdd2: "Tai Seng Exchange (Tower A)",
    SupplierAdd3: "Singapore,SG,New Territories",
    SupplierAdd4: "536464 Singapore",
    SupplierName: "ARROW ELECTRONICS ASIA (S) PTE. LTD.",
    Terms: "FCA",
    TermsofPayment: "90 NET",
  },
  {
    Amount: "240.80",
    InvoiceSlNo: "1",
    ItemCountry: "CN",
    ItemDesc: "Diode Rectifier Bridge Single 600V 6A 4-PinCase GBU",
    ItemHSCODE: "85411000",
    ItemNETWEIGHT: "",
    ItemSlNo: 1,
    PONumber: "4201150489",
    PartNo: "",
    Quantity: "1000",
    Rate: "0.24080",
  },
];
