[
  {
    Branch: "ACC, Chennai",
    CompanyID: "ERI00001",
    CountryOfOrigin: "DK",
    CountryOfShipment: "DK",
    CustomHouse: "null",
    IEC: "null",
    ImporterAdd1: "BP-CP Stock",
    ImporterAdd2: "C/o. FM India Supply Chain Pvt. Ltd",
    ImporterAdd3: "421302 VILLAGE SAPE",
    ImporterAdd4: "BHIWANDI",
    ImporterName: "Siemens Ltd.",
    InvoiceResponseTime: "",
    InvoiceStartTime: "",
    JobNo: "",
    JobStatus: "",
    JobType: "IMP",
    PdfClientName: "SIEMENS LTD",
    PortOfOrgin: "Singapore",
    PortOfShipment: "Singapore",
    TotalCarton: "1",
    TotalGrossWeight: "75,000",
    TotalNetWeight: "66,300",
    UserID: "RTS",
    WorkingPeriod: "null",
  },
];
