[
  {
    Branch: "ACC, Chennai",
    CompanyID: "ERI00001",
    CountryOfOrigin: "DK",
    CountryOfShipment: "DK",
    CustomHouse: "",
    FileName: "SIN-10036551_COMMIN_20250213201731.pdf",
    IEC: "",
    ImporterAdd1: "BP-CP Stock",
    ImporterAdd2: "C/o, FM India Supply Chain Pvt.Ltd",
    ImporterAdd3: "421302 VILLAGE SAPE",
    ImporterAdd4: "BHIWANDI",
    ImporterName: "Siemens Ltd.",
    InvoiceResponseTime: "",
    InvoiceStartTime: "",
    JobNo: "",
    JobStatus: "",
    JobType: "IMP",
    PageCount: "",
    PdfClientName: "SIEMENS LTD",
    PdfCount: "",
    PortOfOrgin: "Singapore",
    PortOfShipment: "Singapore",
    Status: "",
    TotalCarton: "1",
    TotalGrossWeight: "66,300",
    "TotalMeasurement ": "",
    TotalNetWeight: "75,000",
    UserID: "RTS",
    WorkingPeriod: "01-Apr-2024 - 31-Mar-2025",
  },
];
