let inpput = [
  {
    addToTaskList: false,
    name: "Process",
    required: false,
    label: "Process",
    value: "''",
    id: "0",
  },
  {
    addToTaskList: false,
    name: "Task",
    required: true,
    label: "Task",
    value: "{ticketName}",
    id: "1",
  },
  {
    addToTaskList: false,
    name: "Task Description",
    required: true,
    label: "Task Description",
    value: "{ticketDescription}",
    id: "2",
  },
  {
    addToTaskList: false,
    name: "Department",
    required: true,
    label: "Department",
    value: "IT",
    id: "3",
  },
  {
    addToTaskList: false,
    name: "Project",
    required: false,
    label: "Project",
    value: "New",
    id: "4",
  },
  {
    addToTaskList: false,
    name: "Status",
    required: false,
    label: "Status",
    value: "New",
    id: "5",
  },
  {
    addToTaskList: false,
    name: "Start Date",
    required: true,
    label: "Start Date",
    value: "{createdAt}",
    id: "6",
  },
  {
    addToTaskList: false,
    name: "Priority",
    required: true,
    label: "Priority",
    value: "Urgent",
    id: "7",
  },
  {
    addToTaskList: false,
    name: "Due Date",
    required: true,
    label: "Due Date",
    value: "{createdAt+7}",
    id: "8",
  },
  {
    addToTaskList: false,
    name: "Assign To",
    required: true,
    label: "Assign To",
    value: "TVS",
    id: "9",
  },
  {
    addToTaskList: false,
    name: "Attachment",
    required: false,
    label: "Attachment",
    value: [
      {
        docName: "a",
        doc: "s",
        name: "Attachment",
      },
    ],
    id: "10",
  },
  {
    addToTaskList: false,
    name: "Reviewer",
    required: false,
    label: "Reviewer",
    value: "Empty",
    id: "11",
  },
  {
    addToTaskList: false,
    name: "Reviewer Selection Locked",
    required: false,
    label: "Reviewer Selection Locked",
    value: "a",
    id: "12",
  },
  {
    addToTaskList: false,
    name: "Include in Notifications",
    required: false,
    label: "Include in Notifications",
    value: ["TVS"],
    id: "13",
  },
  {
    addToTaskList: false,
    name: "emails",
    required: false,
    label: "emails",
    value: ["priyanka.d@aiqod.com", "test1237@gmail.com"],
    id: "14",
  },
  {
    addToTaskList: false,
    name: "combinedArray",
    required: false,
    label: "combinedArray",
    value: ["TVS:priyanka.d@aiqod.com", ":test1237@gmail.com"],
    id: "15",
  },
  {
    addToTaskList: false,
    name: "names",
    required: false,
    label: "names",
    value: ["TVS", "a"],
    id: "16",
  },
  {
    addToTaskList: false,
    name: "signedinuser",
    required: false,
    label: "signedinuser",
    value: "TVS",
    id: "17",
  },
  {
    addToTaskList: false,
    name: "statusIndex",
    required: false,
    label: "statusIndex",
    value: [1001, 1000, 999, 998],
    id: "18",
  },
  {
    addToTaskList: false,
    name: "combinedstatusobject",
    required: false,
    label: "combinedstatusobject",
    value: {
      New: "998",
      Review: "999",
      Rejected: "1000",
      End: "1001",
    },
    id: "19",
  },
  {
    addToTaskList: false,
    name: "autostransition",
    required: false,
    label: "autostransition",
    value: "z",
    id: "20",
  },
  {
    addToTaskList: false,
    name: "isQueue",
    required: false,
    label: "isQueue",
    value: "a",
    id: "21",
  },
  {
    addToTaskList: false,
    name: "nextStatus",
    required: false,
    label: "nextStatus",
    value: "a",
    id: "22",
  },
  {
    addToTaskList: false,
    name: "indexelem",
    required: false,
    label: "indexelem",
    value: "a",
    id: "23",
  },
  {
    addToTaskList: false,
    name: "assignPro",
    required: false,
    label: "assignPro",
    value: "q",
    id: "24",
  },
  {
    addToTaskList: false,
    name: "owner",
    required: false,
    label: "owner",
    value: "a",
    id: "25",
  },
  {
    addToTaskList: false,
    name: "previousStatus",
    required: false,
    label: "previousStatus",
    value: "a",
    id: "26",
  },
  {
    addToTaskList: false,
    name: "Autotransition to Next Status",
    required: false,
    label: "Autotransition to Next Status",
    value: "a",
    id: "27",
  },
  {
    addToTaskList: false,
    name: "Client name",
    required: true,
    label: "Client name",
    value: "Internal",
    id: "28",
  },
];
let output = inpput.map((item) => item.name);
console.log(JSON.stringify(output));