[
  {
    Branch: null,
    BranchCode: "Acc, Chennai",
    BuyerName: "SENSY S.A.",
    BuyerOrderNo: null,
    CartonNo: 1,
    Client: "GODREJ & BOYCE MFG. CO. LTD.",
    Commission: null,
    CommonItem: null,
    CompanyID: null,
    ConsigneeAdd1: "ZI DE JUMET - ALLEE CENTRALE",
    ConsigneeAdd2: "BE-6040 JUMET (BELGIUM)",
    ConsigneeAdd3: "CHARLEROI BELGIUM",
    ConsigneeAdd4: null,
    ConsigneeName: "SENSY S.A.",
    CountryOfDischarge: "Belgium",
    CountryOfOrigin: null,
    CountryOfShipment: null,
    Currency: "EUR",
    Discount: null,
    ExporterName: "GODREJ & BOYCE MFG. CO. LTD.",
    FileName: null,
    Freight: null,
    GarmentsIGSTPercentage: null,
    HangerIGSTPercentage: null,
    IEC: null,
    Insurance: null,
    InvoiceDate: "04/03/2025",
    InvoiceNo: "1000Q1X11000197",
    InvoiceResponseTime: null,
    InvoiceStartTime: null,
    InvoiceStatus: "Success",
    InvoiceValue: "2010.00",
    JobNo: null,
    JobStatus: "N",
    JobType: "EXP",
    KimballNo: null,
    NotifyAddress1: null,
    NotifyAddress2: null,
    NotifyAddress3: null,
    NotifyAddress4: null,
    NotifyPartyName: null,
    OrderNo: null,
    OtherDed: null,
    OtherReference: null,
    PageCount: 3,
    PaymentPeriod: null,
    PdfClientName: "godrej",
    PdfCount: 1,
    PortOfDischarge: "Mumbai",
    PortOfFinalDestination: "Mumbai",
    PortOfOrgin: null,
    PortOfShipment: null,
    QtyCode: "ECH",
    SchemeCode: null,
    Terms: null,
    TermsOfPayment: "FREE OF COST",
    TotalCBM: null,
    TotalCarton: "1",
    TotalGrossWeight: "1.750",
    TotalNetWeight: "1.000",
    UserID: "c",
    WorkingPeriod: null,
  },
];
