[
  {
    Branch: null,
    BranchCode: "Acc, Chennai",
    BuyerName: "SENSY S.A.",
    BuyerOrderNo: null,
    CartonNo: 1,
    Client: "GODREJ & BOYCE MFG. CO. LTD.",
    Commission: null,
    CommonItem: null,
    CompanyID: null,
    ConsigneeAdd1: "ZI DE JUMET",
    ConsigneeAdd2: "ALLÉE CENTRALE",
    ConsigneeAdd3: "BE-6040 JUMET (BELGIUM)",
    ConsigneeAdd4: "CHARLEROI BELGIUM",
    ConsigneeName: "SENSY S.A.",
    CountryOfDischarge: "Belgium",
    Currency: "EUR",
    Discount: null,
    ExporterName: "GODREJ & BOYCE MFG. CO. LTD.",
    FileName: null,
    Freight: null,
    GarmentsIGSTPercentage: null,
    HangerIGSTPercentage: null,
    IEC: null,
    Insurance: null,
    InvoiceDate: "04/03/2025",
    InvoiceNo: "1000Q1X11000197",
    InvoiceResponseTime: "01/04/2025 18:31:40",
    InvoiceStartTime: "29-07-2024",
    InvoiceValue: "2010.00",
    JobNo: null,
    JobStatus: null,
    JobType: "exp",
    KimballNo: null,
    NotifyAddress1: null,
    NotifyAddress2: null,
    NotifyAddress3: null,
    NotifyPartyName: null,
    OrderNo: null,
    OtherDed: null,
    OtherReference: null,
    PageCount: 3,
    PaymentPeriod: null,
    PdfClientName: "godrej",
    PdfCount: 1,
    PortOfDischarge: "Mumbai",
    PortOfFinalDestination: "Mumbai",
    QtyCode: "ECH",
    SchemeCode: null,
    Status: "success",
    Terms: null,
    TermsOfPayment: "DDP",
    TotalCBM: null,
    TotalCarton: "1",
    TotalGrossWeight: "1.750",
    TotalNetWeight: "1.000",
    UserID: "c",
    WorkingPeriod: null,
  },
];
