[
  {
    Branch: null,
    BranchCode: "Acc, Chennai",
    BuyerName: "MINISTRY OF DEFENCE OF THE REPUBLIC OF ARMENIA",
    BuyerOrderNo: "ARM-01-006",
    CartonNo: "1",
    Client: null,
    Commission: null,
    CommonItem: null,
    CompanyID: null,
    ConsigneeAdd1: "REPUBLIC OF ARMENIA,YEREVAN",
    ConsigneeAdd2: "5, BAGREVAND STR., 0044, YEREVAN",
    ConsigneeAdd3: "ARMENIA",
    ConsigneeAdd4: null,
    ConsigneeName: "MINISTRY OF DEFENCE OF THE REPUBLIC OF ARMENIA",
    CountryOfDischarge: null,
    CountryOfOrigin: "INDIA",
    CountryOfShipment: "INDIA",
    Currency: "USD",
    Discount: null,
    ExporterName: "LARSEN & TOUBRO LIMITED",
    FileName: null,
    Freight: null,
    GarmentsIGSTPercentage: null,
    HangerIGSTPercentage: null,
    IEC: "0388024011",
    Insurance: null,
    InvoiceDate: "19/03/2025",
    InvoiceNo: "TEP24000050",
    InvoiceResponseTime: null,
    InvoiceStartTime: null,
    InvoiceStatus: "Success",
    InvoiceValue: "570,000.00",
    JobNo: null,
    JobStatus: "N",
    JobType: "EXP",
    KimballNo: null,
    NotifyAddress1: null,
    NotifyAddress2: null,
    NotifyAddress3: null,
    NotifyAddress4: null,
    NotifyPartyName: null,
    OrderNo: null,
    OtherDed: null,
    OtherReference: "S067875",
    PageCount: "1 of 1",
    PaymentPeriod: null,
    PdfClientName: "Larsen",
    PdfCount: 1,
    PortOfDischarge: "YEREVAN AIRPORT",
    PortOfFinalDestination: "YEREVAN, ARMENIA",
    PortOfOrgin: "MUMBAI AIRPORT",
    PortOfShipment: "MUMBAI AIRPORT",
    QtyCode: null,
    SchemeCode: null,
    Terms: "FCA",
    TermsOfPayment: null,
    TotalCBM: null,
    TotalCarton: "6",
    TotalGrossWeight: "23,178.600",
    TotalNetWeight: "22,445.600",
    UserID: "c",
    WorkingPeriod: null,
  },
];
