[
  {
    Branch: null,
    BranchCode: "Acc, Chennai",
    CompanyID: null,
    CountryOfOrigin: "INDIA",
    CountryOfShipment: "INDIA",
    Currency: "USD",
    CustomHouse: "YEREVAN AIRPORT",
    FileName: null,
    IEC: "0388024011",
    ImporterAdd1: "REPUBLIC OF ARMENIA, YEREVAN",
    ImporterAdd2: "5, BAGREVAND STR., 0044, YEREVAN",
    ImporterAdd3: "ARMENIA",
    ImporterAdd4: null,
    ImporterName: "MINISTRY OF DEFENCE OF THE REPUBLIC OF ARMENIA",
    InvoiceDate: "19/03/2025",
    InvoiceNo: "TEP24000050",
    InvoiceResponseTime: "02/04/2025 11:52:14",
    InvoiceStartTime: "29-07-2024",
    InvoiceValue: "570,000.00",
    JobNo: null,
    JobStatus: "N",
    JobType: "imp",
    PageCount: 1,
    PdfClientName: "larsen",
    PdfCount: 1,
    PortOfOrgin: "MUMBAI AIRPORT",
    PortOfShipment: "MUMBAI AIRPORT",
    QtyCode: null,
    Status: "Success",
    SupplierName: "LARSEN & TOUBRO LIMITED",
    Terms: "FREE CARRIER (FCA)",
    TotalCarton: "6",
    TotalGrossWeight: "23,178.600",
    TotalMeasurement: null,
    TotalNetWeight: "22,445.600",
    UserID: "c",
    WorkingPeriod: null,
  },
];
