[
  {
    Branch: "",
    BranchCode: "Acc, Chennai",
    BuyerName: "",
    BuyerOrderNo: "",
    CartonNo: "1",
    Client: "SIEMENS HEALTHCARE PRIVATE LIMITED",
    Commission: "",
    CommonItem: "",
    CompanyID: null,
    ConsigneeAdd1: "WORLD DISTRIBUTION CENTER,",
    ConsigneeAdd2: "HALLE A2, TOR 8-14,",
    ConsigneeAdd3: "AN DER GEHESPITZ 90, 63263,NEU - ISENBURG, ",
    ConsigneeAdd4: "GERMANY.",
    ConsigneeName: "SIEMENS HEALTHINEERS AG,",
    CountryOfDischarge: "GERMANY.",
    Currency: "USD",
    Discount: null,
    ExporterName: "SIEMENS HEALTHCARE PRIVATE LIMITED",
    FileName: "",
    Freight: "",
    GarmentsIGSTPercentage: null,
    HangerIGSTPercentage: null,
    IEC: "0315054191",
    Insurance: "",
    InvoiceDate: "20-03-2025",
    InvoiceNo: "SH-SER-01-25/102",
    InvoiceResponseTime: "16/03/2025 11:14:22",
    InvoiceStartTime: "29-07-2024",
    InvoiceValue: "96,469.67",
    JobNo: null,
    JobStatus: null,
    JobType: "exp",
    KimballNo: null,
    NotifyAddress1: null,
    NotifyAddress2: null,
    NotifyAddress3: null,
    NotifyPartyName: null,
    OrderNo: "",
    OtherDed: "",
    OtherReference: "",
    PageCount: 11,
    PaymentPeriod: "30",
    PdfClientName: "SIEMENS HEALTHCARE PRIVATE LIMITED",
    PdfCount: 1,
    PortOfDischarge: "FRANKFURT",
    PortOfFinalDestination: "",
    QtyCode: "",
    SchemeCode: null,
    Status: "Success",
    Terms: "",
    TermsOfPayment: "DAP",
    TotalCBM: "",
    TotalCarton: "",
    TotalGrossWeight: "",
    TotalNetWeight: "",
    UserID: "c",
    WorkingPeriod: null,
  },
];
