[
  {
  Branch: '',
  BranchCode: 'Acc, Chennai',
  BuyerName: '',
  BuyerOrderNo: '',
  CartonNo: '1',
  Client: 'SIEMENS HEALTHCARE PRIVATE LIMITED',
  Commission: '',
  CommonItem: '',
  CompanyID: null,
  ConsigneeAdd1: 'WORLD DISTRIBUTION CENTER,',
  ConsigneeAdd2: 'HALLE A2, TOR 8-14,',
  ConsigneeAdd3: 'AN DER GEHESPITZ 90, 63263,',
  ConsigneeAdd4: 'GERMANY.',
  ConsigneeName: 'SIEMENS HEALTHINEERS AG,',
  CountryOfDischarge: 'GERMANYE',
  Currency: 'USD',
  Discount: null,
  ExporterName: 'SIEMENS HEALTHCARE PRIVATE LIMITED',
  FileName: null,
  Freight: '',
  GarmentsIGSTPercentage: null,
  HangerIGSTPercentage: null,
  IEC: '0315054191',
  Insurance: '',
  InvoiceDate: '20-03-2025',
  InvoiceNo: 'SH-SER-01-25/102',
  InvoiceResponseTime: null,
  InvoiceStartTime: null,
  InvoiceValue: '96,469.67',
  JobNo: null,
  JobStatus: 'N',
  JobType: 'EXP',
  KimballNo: null,
  NotifyAddress1: null,
  NotifyAddress2: null,
  NotifyAddress3: null,
  NotifyAddress4: null,
  NotifyPartyName: null,
  OrderNo: 'NA',
  OtherDed: '',
  OtherReference: null,
  PageCount: 11,
  PaymentPeriod: '30',
  PdfClientName: 'SIEMENS HEALTHCARE PRIVATE LIMITED',
  PdfCount: 1,
  PortOfDischarge: 'FRANKFURT',
  PortOfFinalDestination: '',
  QtyCode: null,
  SchemeCode: null,
  Terms: null,
  TermsOfPayment: 'DAP',
  TotalCBM: '',
  TotalCarton: '',
  TotalGrossWeight: null,
  TotalNetWeight: null,
  UserID: 'c',
  WorkingPeriod: null
}
];
