[
  {
    Branch: null,
    BranchCode: "Acc, Chennai",
    BuyerName: "Siemens Limited",
    BuyerOrderNo: "",
    CartonNo: "1",
    Client: "SIEMENS LIMITED",
    Commission: "",
    CommonItem: "",
    CompanyID: null,
    ConsigneeAdd1: "Charn Issara Tower II, 32nd FI",
    ConsigneeAdd2: "2922/320-323 New Petchburi Road,",
    ConsigneeAdd3: "Bangkapi Huaykwang ,",
    ConsigneeAdd4: "Bangkok 10310",
    ConsigneeName: "Siemens Limited",
    CountryOfDischarge: "Thailand",
    CountryOfOrigin: null,
    CountryOfShipment: null,
    Currency: "EUR",
    Discount: null,
    ExporterName: "SIEMENS LIMITED",
    FileName: null,
    Freight: "",
    GarmentsIGSTPercentage: null,
    HangerIGSTPercentage: null,
    IEC: "0388070005",
    Insurance: "",
    InvoiceDate: "20.03.2025",
    InvoiceNo: "MH1427278614",
    InvoiceResponseTime: null,
    InvoiceStartTime: null,
    InvoiceStatus: "Success",
    InvoiceValue: "9,571.89",
    JobNo: null,
    JobStatus: "N",
    JobType: "EXP",
    KimballNo: null,
    NotifyAddress1: null,
    NotifyAddress2: null,
    NotifyAddress3: null,
    NotifyAddress4: null,
    NotifyPartyName: null,
    OrderNo: "",
    OtherDed: "",
    OtherReference: "",
    PageCount: 19,
    PaymentPeriod: "30",
    PdfClientName: "SIEMENS LIMITED",
    PdfCount: 1,
    PortOfDischarge: "Bangkok",
    PortOfFinalDestination: null,
    PortOfOrgin: null,
    PortOfShipment: null,
    QtyCode: "PC",
    SchemeCode: null,
    Terms: "FCA",
    TermsOfPayment: null,
    TotalCBM: "",
    TotalCarton: null,
    TotalGrossWeight: null,
    TotalNetWeight: null,
    UserID: "c",
    WorkingPeriod: null,
  },
];
