[
  {
    Branch: "",
    BranchCode: "Acc, Chennai",
    BuyerName: "",
    BuyerOrderNo: "",
    CartonNo: "1",
    Client: "SIEMENS LIMITED",
    Commission: "",
    CompanyID: null,
    ConsigneeAdd1: "Charn Issara Tower II, 32nd Fl",
    ConsigneeAdd2: "2922/320-323 New Petchburi Road,",
    ConsigneeAdd3: "AN DER GEHESPITZ 90, 63263,NEU - ISENBURG, ",
    ConsigneeAdd4: "Thailand",
    ConsigneeName: "Siemens Limited",
    CountryOfDischarge: "Thailand.",
    Currency: "EUR",
    Discount: null,
    ExporterName: "SIEMENS LIMITED",
    FileName: "",
    Freight: "",
    GarmentsIGSTPercentage: null,
    HangerIGSTPercentage: null,
    IEC: "0388070005",
    Insurance: "",
    InvoiceDate: "20.03.2025",
    InvoiceNo: "MH1427278614",
    InvoiceResponseTime: "16/03/2025 11:14:22",
    InvoiceStartTime: "29-07-2024",
    InvoiceValue: "9,571.89",
    JobNo: null,
    JobStatus: null,
    JobType: "exp",
    KimballNo: null,
    NotifyAddress1: null,
    NotifyAddress2: null,
    NotifyAddress3: null,
    NotifyPartyName: null,
    OrderNo: "",
    OtherReference: "",
    PageCount: 19,
    PaymentPeriod: "30",
    PdfClientName: "SIEMENS LIMITED",
    PdfCount: 1,
    PortOfDischarge: "Bangkok",
    PortOfFinalDestination: "",
    QtyCode: "PC",
    SchemeCode: null,
    Status: "Success",
    Terms: "FCA",
    TermsOfPayment: "",
    TotalCBM: "",
    TotalCarton: "",
    TotalGrossWeight: "",
    TotalNetWeight: "",
    UserID: "c",
    WorkingPeriod: null,
    CommonItem: "",
    OtherDed: "",
  },
];
