[
  {
    Branch: null,
    BranchCode: "Acc, Chennai",
    BuyerName: null,
    BuyerOrderNo: null,
    CartonNo: 1,
    Client: "Siemens Healthcare Pvt. Ltd.",
    Commission: null,
    CommonItem: null,
    CompanyID: null,
    ConsigneeAdd1: "500 GBC Drive,",
    ConsigneeAdd2: "Lab 420, M/S 521",
    ConsigneeAdd3: "Newark, DE 19702-6101",
    ConsigneeAdd4: "USA",
    ConsigneeName: "Siemens Healthcare Diagnostics",
    CountryOfDischarge: "USA",
    Currency: "USD",
    Discount: null,
    ExporterName: "Siemens Healthcare Pvt. Ltd.,",
    FileName: null,
    Freight: null,
    GarmentsIGSTPercentage: null,
    HangerIGSTPercentage: null,
    IEC: "0315054191",
    Insurance: null,
    InvoiceDate: "14-Jan-25",
    InvoiceNo: "EXPGGNDX14012501",
    InvoiceResponseTime: "02/04/2025 13:26:16",
    InvoiceStartTime: "29-07-2024",
    InvoiceValue: "2.00",
    JobNo: null,
    JobStatus: null,
    JobType: "exp",
    KimballNo: null,
    NotifyAddress1: null,
    NotifyAddress2: null,
    NotifyAddress3: null,
    NotifyPartyName: null,
    OrderNo: null,
    OtherDed: null,
    OtherReference: null,
    PageCount: 1,
    PaymentPeriod: null,
    PdfClientName: "siemens healthcare pvt ltd",
    PdfCount: 1,
    PortOfDischarge: "Mumbai",
    PortOfFinalDestination: "",
    QtyCode: "Box",
    SchemeCode: null,
    Status: "success",
    Terms: "FOC",
    TermsOfPayment: null,
    TotalCBM: null,
    TotalCarton: "1",
    TotalGrossWeight: "11",
    TotalNetWeight: "1",
    UserID: "c",
    WorkingPeriod: null,
  },
];
