[
  {
    Branch: null,
    BranchCode: "Acc, Chennai",
    BuyerName: null,
    BuyerOrderNo: null,
    CartonNo: 1,
    Client: "Siemens Healthcare Pvt. Ltd.",
    Commission: null,
    CommonItem: null,
    CompanyID: null,
    ConsigneeAdd1: "500 GBC Drive,Lab 420, M/S 521",
    ConsigneeAdd2: "Newark, DE 19702-6101",
    ConsigneeAdd3: "USA",
    ConsigneeAdd4: "",
    ConsigneeName: "Siemens Healthcare Diagnostics",
    CountryOfDischarge: "USA",
    CountryOfOrigin: null,
    CountryOfShipment: null,
    Currency: "USD",
    Discount: null,
    ExporterName: "Siemens Healthcare Pvt. Ltd.,",
    FileName: null,
    Freight: null,
    GarmentsIGSTPercentage: null,
    HangerIGSTPercentage: null,
    IEC: "0315054191",
    Insurance: null,
    InvoiceDate: "14-Jan-25",
    InvoiceNo: "EXPGGNDX14012501",
    InvoiceResponseTime: null,
    InvoiceStartTime: null,
    InvoiceStatus: "Success",
    InvoiceValue: "2.00",
    JobNo: null,
    JobStatus: "N",
    JobType: "EXP",
    KimballNo: null,
    NotifyAddress1: null,
    NotifyAddress2: null,
    NotifyAddress3: null,
    NotifyAddress4: null,
    NotifyPartyName: null,
    OrderNo: null,
    OtherDed: null,
    OtherReference: null,
    PageCount: 1,
    PaymentPeriod: null,
    PdfClientName: "siemens healthcare pvt ltd",
    PdfCount: 1,
    PortOfDischarge: "Mumbai",
    PortOfFinalDestination: null,
    PortOfOrgin: null,
    PortOfShipment: null,
    QtyCode: "Box",
    SchemeCode: null,
    Terms: "FOC",
    TermsOfPayment: null,
    TotalCBM: null,
    TotalCarton: "1",
    TotalGrossWeight: "11",
    TotalNetWeight: "1",
    UserID: "c",
    WorkingPeriod: null,
  },
];
