[
  {
    Branch: null,
    BranchCode: "Acc, Chennai",
    CompanyID: null,
    CountryOfOrigin: "INDIA",
    CountryOfShipment: "INDIA",
    Currency: "$",
    CustomHouse: "Kuala Lumpur Airport",
    FileName: null,
    IEC: null,
    ImporterAdd1: "No. 50, Lorong Machang Indah 8,",
    ImporterAdd2: "Taman Perindustrian Machang Indah,",
    ImporterAdd3: "14000 Bukit Mertajam, Pulau Pinang.",
    ImporterAdd4: "Malaysia",
    ImporterName: "NEW SEASON SDN BHD",
    InvoiceDate: "07.03.2025",
    InvoiceNo: "G/24-25/EXP/091",
    InvoiceResponseTime: "02/04/2025 11:54:35",
    InvoiceStartTime: "29-07-2024",
    InvoiceValue: "1,432.50",
    JobNo: null,
    JobStatus: "N",
    JobType: "imp",
    PageCount: 1,
    PdfClientName: "top syringe",
    PdfCount: 1,
    PortOfOrgin: "Mumbai - India",
    PortOfShipment: "Mumbai - India",
    QtyCode: null,
    Status: "Success",
    SupplierName: "TOP SYRINGE MFG CO PVT LTD",
    Terms: null,
    TotalCarton: "2",
    TotalGrossWeight: null,
    TotalMeasurement: null,
    TotalNetWeight: null,
    UserID: "c",
    WorkingPeriod: null,
  },
];
