[
  {
    Branch: null,
    BranchCode: "Acc, Chennai",
    BuyerName: null,
    BuyerOrderNo: "PO-2502/019",
    CartonNo: null,
    Client: null,
    Commission: null,
    CommonItem: null,
    CompanyID: null,
    ConsigneeAdd1: "No. 50, Lorong Machang Indah 8,",
    ConsigneeAdd2: "Taman Perindustrian Machang Indah,",
    ConsigneeAdd3: "14000 Bukit Mertajam, Pulau Pinang.",
    ConsigneeAdd4: "Malaysia",
    ConsigneeName: "NEW SEASON SDN BHD",
    CountryOfDischarge: "Malaysia",
    CountryOfOrigin: "INDIA",
    CountryOfShipment: "INDIA",
    Currency: "$",
    Discount: null,
    ExporterName: "TOP SYRINGE MFG CO PVT LTD",
    FileName: null,
    Freight: null,
    GarmentsIGSTPercentage: null,
    HangerIGSTPercentage: null,
    IEC: null,
    Insurance: null,
    InvoiceDate: "07.03.2025",
    InvoiceNo: "G/24-25/EXP/091",
    InvoiceResponseTime: null,
    InvoiceStartTime: null,
    InvoiceStatus: "Success",
    InvoiceValue: "1,432.50",
    JobNo: null,
    JobStatus: "N",
    JobType: "EXP",
    KimballNo: null,
    NotifyAddress1: null,
    NotifyAddress2: null,
    NotifyAddress3: null,
    NotifyAddress4: null,
    NotifyPartyName: null,
    OrderNo: null,
    OtherDed: null,
    OtherReference: null,
    PageCount: "1",
    PaymentPeriod: null,
    PdfClientName: "top syringe",
    PdfCount: "1",
    PortOfDischarge: "Kuala Lumpur Airport",
    PortOfFinalDestination: null,
    PortOfOrgin: "Mumbai - India",
    PortOfShipment: "Mumbai - India",
    QtyCode: "PCS",
    SchemeCode: null,
    Terms: null,
    TermsOfPayment: null,
    TotalCBM: null,
    TotalCarton: "2",
    TotalGrossWeight: null,
    TotalNetWeight: null,
    UserID: "c",
    WorkingPeriod: null,
  },
];
